### ISSUE TITLE
Quick Cache taking down website!

### ISSUE THREAD

**Issue by rideralberta** [wpsharks/comet-cache#419]
Wow... For the second time, after running a Quick Cache update, my website has been taken down. Even tech support there can't fix the problem, other than going to a server backup and restoring a folder. What on earth is in your code to put us offline?? We just get a blank page after updating.

**Comment by raamdev** [comment]
@rideralberta I've never seen or heard of such an issue and we have thousands of sites running Quick Cache Pro. 

I'm surprised your host's tech support wasn't able to give you any clues. The log files on the server will indicate the reason for the "blank page" that you're seeing, so that would be the first place I'd look for clues. You may also want to enable WordPress debugging

Try enabling WordPress debugging by adding the following lines to your `wp-config.php` file then attempt to run the auto-update mechanism again and check the `wp-content/debug.log` file for any further messages that might be related to this error.

```
define('WP_DEBUG', true); // enables debugging
define('WP_DEBUG_LOG', true); // logs messages to wp-content/debug.log
define('WP_DEBUG_DISPLAY', false); // hides debug messages from showing in the browser
```

See also: https://codex.wordpress.org/Debugging_in_WordPress

---

At the very least, to get your site up and running again, you can follow these emergency uninstallation instructions:

**EMERGENCY: If all else fails, how can I remove Quick Cache?**

Ordinarily you can just deactivate Quick Cache from the plugins menu in WordPress. However, if you're having a more serious issue, please follow the instructions here.
- Log into your site via FTP; perhaps using [FileZilla](https://www.youtube.com/watch?v=joXUMhr8PhU).
- Delete this file: `/wp-content/advanced-cache.php`
- Delete this directory: `/wp-content/plugins/quick-cache/`
- Remove this line from your /`wp-config.php` file: `define('WP_CACHE', TRUE);`

Quick Cache is now completely uninstalled and you can start fresh.

---

I'm not seeing a bug here, so I'm going to mark this issue as closed (we reserve GitHub for bug reports). However, please do [open a support ticket](https://www.websharks-inc.com/support/?product=quick-cache&request_type=trouble_ticket) if you continue to have problems and need support. We're happy to help.

**Comment by rideralberta** [comment]
I will forward this to them. This is the second time that updating your plugin has done this. We lost four hours work today and so switched to WP-Cache. 

Mark

---

www.markmallett.com http://www.markmallett.com/

**Comment by rideralberta** [comment]
Why would you close this??

Mark

---

www.markmallett.com http://www.markmallett.com/

**Comment by raamdev** [comment]
@rideralberta I just explained why I closed it:

I'm not seeing a bug here, so I'm going to mark this issue as closed (we reserve GitHub for bug reports). However, please do open a support ticket if you continue to have problems and need support. We're happy to help.

**Comment by rideralberta** [comment]
okee dokee. 

Mark

---

www.markmallett.com http://www.markmallett.com/
