### ISSUE TITLE
Nginx with Quickcache

### ISSUE THREAD

**Issue by EtixPP** [wpsharks/comet-cache#421]
Hello,
i just changed my apache system to nginx and basicly everything works, just... as i already expected quick cache, which worked perfectly on apache, does not print the comment line that it works anymore, so i highly suggest that it doesnt (i can see it on the loadtime aswell).

Do you have any suggestions what i could to do possibly fix this issue?
I am a pro user.

Kind Regards,
Alex

**Comment by raamdev** [comment]
@EtixPP We've tested Quick Cache with Nginx and we haven't seen any issues. Quick Cache is compatible with Nginx and runs just fine. 

It could be that Nginx isn't configured properly on your server or that you have something else stripping out the HTML comments in the source code, thereby hiding the messages that Quick Cache is adding to indicate that it's working as expected.

---

We reserve GitHub for filing bug reports and making feature requests. Since you are a Quick Cache Pro user, please open a [Trouble Ticket](https://www.websharks-inc.com/support/?product=quick-cache&request_type=trouble_ticket) and we'll see if there's anything we can do to help you resolve this. Thank you! :)
