### ISSUE TITLE
Broken RSS feeds when using gzip

### ISSUE THREAD

**Issue by pommes** [wpsharks/comet-cache#422]
I use quick-cache but as suggested disabled it for my RSS feeds.
My problem now is that quick-cache adds a HTML comment to the feed like:

``` html
<!-- Quick Cache is NOT caching this page, because `$_SERVER['REQUEST_URI']` indicates this is a `/feed`; and the configuration of this site says not to cache XML-based feeds. -->
```

This breaks my RSS feed when my http server (nginx) is configured to send content gziped. It seems that it adds the comment after the server gzipped the stream. Is that possible?
It is not not a problem for every browser but for example for [BeyondPod](http://www.beyondpod.mobi/).

I found the same problem [here](https://groups.google.com/forum/#!topic/feedvalidator-users/SMptmoV8oUQ).

I would prefer that quick-cache leaves my RSS feeds alone when I set the option: _Leave my RSS feeds alone_. ;-)

**Comment by jaswrks** [comment]
@pommes You can disable those debug notes also.
See: **Dashboard ⥱ Quick Cache ⥱ Enable/Disable ⥱** Choose the _No_ option where it asks if you want to include the debug notes in the comments.

**Comment by pommes** [comment]
Ah cool. Did not see that. Are those debug notes new? Maybe it's safer to turn it off by default.
But that did it for me.
Thanx!

**Comment by raamdev** [comment]
@pommes The debug notes have always been there and the default has always been to show them. :-) That is the safest option because it allows site owners to verify that Quick Cache is actually caching the page.

That said, I do see the value in being able to disable those notes for requests that are being excluded from the cache. I've gone ahead and filed a feature request to add this functionality at a future time. See https://github.com/websharks/quick-cache/issues/423.
