### ISSUE TITLE
Show Dashboard message when conflicting caching plugin is detected

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#428]
<del>I've heard a few reports of Quick Cache and ZenCache being installed on WordPress sites that were already running a caching plugin (such as WP Super Cache and W3TC) and instead of reporting an error message, Quick Cache / ZenCache just appeared active in the plugins list but did not show up in the sidebar. </del>

<del>This needs further testing. We should detect conflicting caching plugins and report that only one caching plugin can be active at once.</del>

<del>Some web hosts bundle caching plugins with automated-WordPress installs, so sometimes a site owner might not even be aware they're already running a caching plugin.</del>

This is already implemented:
- Referencing: https://github.com/websharks/zencache/blob/000000-dev/zencache/includes/conflicts-check.php

However no Dashboard message is shown when a conflicting plugin is detected and deactivated.
- [ ] Display Dashboard message when conflict plugin is detected and deactivated
- [ ] Test the detection process by installing a conflicting caching plugin and attempting to activate ZenCache

**Comment by jaswrks** [comment]
> We should detect conflicting caching plugins and report that only one caching plugin can be active at once.

Referencing: https://github.com/websharks/zencache/blob/000000-dev/zencache/includes/conflicts-check.php

This is something that ZenCache does already, but we might need to add other plugin slugs to the list.

**Comment by raamdev** [comment]
> Referencing: https://github.com/websharks/zencache/blob/000000-dev/zencache/includes/conflicts-check.php

I see that no Dashboard message is displayed when a conflicting plugin is detected and deactivated. We should definitely add a Dashboard message here.

I'll update the title of this issue.

**Comment by jaswrks** [comment]
> I see that no Dashboard message is displayed when a conflicting plugin is detected and deactivated. We should definitely add a Dashboard message here.

There is a Dashboard message also, it's just not in that particular file.
Referencing: https://github.com/websharks/zencache/blob/000000-dev/zencache/zencache.inc.php#L2344

![2015-03-04_20-07-53](https://cloud.githubusercontent.com/assets/1563559/6499577/3df0daee-c2aa-11e4-8581-f0b7ffb5434f.png)

---

There is no Dashboard notice for Quick Cache or Quick Cache Pro though, because these get deactivated automatically; i.e., they don't actually introduce a conflict, because we disable them automatically. The others are not disabled or deactivated. We just show a notice.

**Comment by raamdev** [comment]
@jaswsinc Thanks for following up here. :-) I'm not sure how I missed the Dashboard message... I think I'm the one who helped write the message itself!
