### ISSUE TITLE
Exclude domains in multisite

### ISSUE THREAD

**Issue by SnakeO** [wpsharks/comet-cache#437]
Hello, I have the pro-version and I'm trying to exclude only certain domains from being cached in my multisite userbase. How can I do this?

**Comment by raamdev** [comment]
@SnakeO There is a feature request open for this here: https://github.com/websharks/zencache/issues/343

There's also a temporary workaround that you can use while we work on getting this feature implemented on in the ZenCache options.

I suggest you click the "Subscribe" button on that feature request so that you can be notified when it is updated.
