### ISSUE TITLE
Latest release of Zencache html compression breaks css styles on site and generates php error

### ISSUE THREAD

**Issue by akrakar1** [wpsharks/comet-cache#474]
Hi, the Zencache HTML compression was working great till I updated to WordPress 4.1.2. Now if I use HTML compression with the same settings that worked previously, my pages render very poorly with the CSS styles mixed up and the home page shows this error message under the footer:
Fatal error: Uncaught exception 'websharks\html_compressor\js_minifier_string_e' with message 'js_minifier: Unterminated String at byte 206: '' in /data/21/2/83/34/2083360/user/2284238/htdocs/wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/externals/js-minifier.php:148 Stack trace: #0 /data/21/2/83/34/2083360/user/2284238/htdocs/wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/externals/js-minifier.php(99): websharks\html_compressor\js_minifier->action(1) #1 /data/21/2/83/34/2083360/user/2284238/htdocs/wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/externals/js-minifier.php(39): websharks\html_compressor\js_minifier->min() #2 /data/21/2/83/34/2083360/user/2284238/htdocs/wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/core.php(1946): websharks\html_compressor\js_minifier::compress('jQuery(document...') #3 /data/21/2/83/34/2083360/user/2284238/htdocs/wp-content/plugins/zencache-pro/ in /data/21/2/83/34/2083360/user/2284238/htdocs/wp-content/plugins/zencache-pro/submodules/html-compressor/html-compressor/includes/externals/js-minifier.php on line 148
If I turn off the HTML compression feature, my cached pages render correctly again. There is definitely something in the HTML compression code that is not working correctly any longer.

**Comment by raamdev** [comment]
@akrakar1 Thank you for the bug report! 

Can you please test this issue in a clean WordPress installation (i.e., running the default WordPress TwentyFifteen theme with no other plugins except ZenCache active)? I'd like to rule out the possibility that another one of your plugins, or your theme, is introducing a conflict with ZenCache.

We haven't been able to reproduce this issue in our test environments.

**Comment by akrakar1** [comment]
Hi, Raam Dev.

I don’t personally have time to create a new WordPress install. I’m a one-person web management team with additional duties and very limited time.
If it’s not an issue that can be resolved without a lot of testing, it would make sense to me to find a different caching program with a more stable HTML compression feature. What makes me upset is that I paid for your pro version, and our site was messed up for 3 days with zero possibility for people to apply for jobs, schedule donation pickups, etc. with my company. At the very least there should be a notice in the plugin that HTML compression should be retested whenever WordPress or any plugins are updated because fatal PHP errors may occur and take down your site. Unfortunately I didn’t realize there was a problem until someone notified me because I was logged into WordPress and seeing the PHP pages.

Regards,

Amy Krakar
Web Specialist
Hope Services
408.284.2877
akrakar@hopeservices.orgmailto:akrakar@hopeservices.org

[cid:image004.jpg@01D0827F.15A29B60]

Shop through Amazon Smile and Amazon donates 0.5% of the proceeds of your purchase to Hope Services. Click below to link directly to Hope’s Amazon Smile account!!!
http://smile.amazon.com/ch/94-1399287

**Comment by jaswrks** [comment]
> Uncaught exception 'websharks\html_compressor\js_minifier_string_e' with message 'js_minifier: Unterminated String at byte 206

I'd suggest two things:
- Make sure you're running the latest release of ZenCache, because this error should no longer show up in the most recent versions. It's triggered by syntax errors in JavaScript, and we now skip over this silently.
- Look for the syntax errors in the JavaScript that is being compressed. That is actually the underlying cause of this error message. It's the HTML Compressor tripping on errors in a JavaScript file it is compressing.

**Comment by raamdev** [comment]
@akrakar1 

> At the very least there should be a notice in the plugin that HTML compression should be retested whenever WordPress or any plugins are updated because fatal PHP errors may occur and take down your site.

Re-testing all primary functions of your site after installing a new plugin or changing some functionality from the WordPress Dashboard is something that should be done regardless of what plugin you're using. There are also lots of ways you can setup error reporting on your server so that you are emailed whenever an error occurs (this is something you can setup with your web hosting company). It's not possible for ZenCache or the HTML Compressor to consider every possible scenario where there might be an error.

Also, it is clearly indicated (twice) inside the HTML Compressor options panel that the HTML Compressor is an experimental feature. While the feature is extremely stable and we consider it ready for production (we use it on all of our production websites and have never had any issues), we still want site owners to realize that compressing CSS and JavaScript is more prone to errors and ZenCache simply cannot predict all possible scenarios (e.g., in your case it sounds like there is some JavaScript file on your site that contains some syntax errors).

![2015-04-30_22-28-35](https://cloud.githubusercontent.com/assets/53005/7425945/e19b5984-ef88-11e4-92fa-4011941b9c0b.png)

As Jason suggested above:
- Make sure you're running the latest release of ZenCache, because this error should no longer show up in the most recent versions. It's triggered by syntax errors in JavaScript, and we now skip over this silently.
- Look for the syntax errors in the JavaScript that is being compressed. That is actually the underlying cause of this error message. It's the HTML Compressor tripping on errors in a JavaScript file it is compressing.
