### ISSUE TITLE
Logged-In User Cache files are regenerated upon each login

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#476]
### Steps to reproduce this bug

_Tested with ZenCache Pro v150409, WP v4.2.1 Single-Site install._
1. Enable Logged-In User Caching (**ZenCache → Plugin Options → Logged-In Users), setting it to "maintain a separate cache for each user"
2. Visit some pages on the site to generate some user-specific cache files; make note of the timestamp on the generated cache files (either on the filesystem or by View Source and noting the cache file generation timestamp at the bottom)
3. Logout and then back in as the same user
4. Visit the same pages on the site
### Expected Behavior

The existing cache file(s) should be served to the user, as nothing has changed on the site.
### Observed Behavior

The cache file for each page visited is regenerated (based on the timestamp changing to the current time). Instead of serving the existing cache file, the cache file is regenerated. 

---
### Support threads referencing this issue
- https://websharks.zendesk.com/agent/tickets/6063 (internal ticket)

**Comment by jaswrks** [comment]
> Logout and then back in as the same user

This is to be expected. Any `POST` forces a full refresh of the cache for that user. So logging out, fine. Logging back in is a new `POST` and this will trigger a clearing of the cache for that user on purpose.

Any sort of `POST` would imply that something is being submitted by the user. Thus, there is reason to assume that all cache entries might need to be updated. For instance, the `POST` might have been to update their profile, which could impact things displayed on-site for that user.

Another example would be if you listed the "number of times they logged in" somewhere. Logging back into the site will alter this. ZenCache has to assume that the entire cache needs to be cleared in this case. So any `POST` request will cause this.

The same is true for any `GET` request with query string variables, whenever the site is running (by default) with GET requests off in your ZenCache configuration.

Referencing: https://github.com/websharks/zencache-pro/blob/150409/zencache-pro/includes/advanced-cache.tpl.php#L923

**Comment by erikture** [comment]
If this is the excpected behaviour then the caching of logged in users is totaly useless. In most cases the cache will actually slow down the site not speed it up. The only time it will speed it up is if a user access the same page several times during a session. The first time will take much longer time than if there was no cache at all. The next times will get faster, but how many times does a user visit the same page several times during a session. And how often does he access it that many times so the total time gets less with the cache on than with the cache off.

If the site contains dynamic data like the number of times a user loggs in then caching logged in users are not to be choosen because then you need a dynamic site not a static site.

**Comment by jaswrks** [comment]
> If this is the excpected behaviour then the caching of logged in users is totaly useless. In most cases the cache will actually slow down the site not speed it up.

I disagree. While it might be true in a few specific cases, for most sites, the number of times that a user does a `POST` request is very low when compared to the number of pages they visit while logged-in. For instance, consider a social networking site (e.g., a site running BuddyPress). Lots of user-specific page views on a site like this, with very few `POST` requests. When a `POST` does occur, the cache must be cleared, as any form submission could have an impact on output generated by a theme.

I'm open to suggestions on how to better handle this though. Do you have ideas you'd like to share?

---

> If the site contains dynamic data like the number of times a user loggs in then caching logged in users are not to be choosen because then you need a dynamic site not a static site.

_Any_ site that allows users to log in (e.g., a membership site or social network) requires a dynamic site. ZenCache is making it possible for you to serve some of those statically in an intelligent way. That's improving speed! — for a site that would otherwise require all dynamic content at all times.

---

Also, keep in mind that logging _out_ of a site is not something that every user does. For those that do, when they return to the site and log in again, the cache will be reset. However, there is a large percentage of users that will not be logging in/out all of the time. They can close their browser, leave for two days, return later, and they are still logged in, and the cache remains from 2 days prior :-)

**Comment by raamdev** [comment]
@jaswsinc Thanks for the clarification. After hearing your explanation about any `POST` requiring the cache to be cleared, I somewhat agree with the current behavior. 

However, I am curious why logging in is considered a `POST` (besides the obvious fact of `POST`ing their login credentials to login). It seems to me that the behavior that makes the most sense is to _not_ clear the users cache for a login, but always clear that users cache for any `POST` made thereafter (once they're logged in). That way, if they never `POST` anything after logging in, they'll just use the existing cache. 

> Another example would be if you listed the "number of times they logged in" somewhere. Logging back into the site will alter this. ZenCache has to assume that the entire cache needs to be cleared in this case. So any POST request will cause this.

But how would that scenario be any different than, say, a site owner running a plugin with a "page view counter" and complaining that the page view counter isn't refreshing? It seems to me that if a site owner is running a plugin or has some code that tells visitors how many times they've logged in, and they're using ZenCache Logged-In User Caching, they should need to write some custom code to clear the users cache upon login. As for other pages or content that may be updated while the user was logged out, we already handle that by clearing the cache for that specific Post/Page when that event occurs, which includes clearing any related user-specific cache files as well.

What other common scenarios can you think of that would require a users cache to be cleared immediately upon login?

**Comment by jaswrks** [comment]
> However, I am curious why logging in is considered a POST (besides the obvious fact of POSTing their login credentials to login).

From a broader perspective, any `POST` from a user is the user submitting something to your site in one way or another. This implies that your server is receiving this data and performing some action on the server side. Thus, it is relatively safe to assume that something is most likely changing for that user. Whether it be with their profile, with stats that you keep, or with the page they receive as output from that `POST` submission. Very difficult to predict what might be taking place on any given site.

> But how would that scenario be any different than, say, a site owner running a plugin with a "page view counter" and complaining that the page view counter isn't refreshing?

Not really any different in that particular example. It was just one example though. The thought process here is that is we _do not know_ what is changing, and it's better to error on the side of being wrong about something changing, then to _hope_ that nothing is. Being wrong in a case like this does no harm at all anyway.

> What other common scenarios can you think of that would require a users cache to be cleared immediately upon login?

A better example might be...
- User logs into site via `POST` submission.
- Upon logging in, the number of logins is determined to be `5`, and the user is redirected to a page that renders content based on the total number of logins they have. This is actually a feature in the s2Member plugin for WordPress, where special offers are introduced after X number of logins. Conditionals in any content on the site, whether it be on a stand-alone page or in some other dynamic element on the site that is adjusted based on data associated with the current user. This data may or may not consider properties that change when the user logs in. I don't see any choice but to assume that the cache needs to be cleared in a scenario like this.
  - There is also the potential for some other theme/plugin to serve widget content that changes based on the number of logins. Or, on the user's current IP address that is actually recorded only during the login `POST` request.

Another thing to consider is _how_ you would even detect what is _just_ a login and not a `POST` that is actually performing two or three actions, in addition to logging the user in. If it's a `POST` request, I guess you could look for a `POST` array that contains only the `user`, `pwd` elements—assuming that we are looking for `/wp-login.php` logins (which is not always an accurate assumption).

Anyway, that has a bad smell to it in my opinion. I think that any `POST` request (or any uncacheable request type, for that matter) should trigger a full wipe of the cache for that user. Caching logged-in users is already an oxymoron so-to-speak. With this feature, we are pushing the limits of what a page cache can do. Trying to preserve the cache even after we _know_ that a user `POST`d something to the server seems like it is asking for trouble.

All of that said, I am very open to hearing ideas on how to handle this. Nothing comes to my mind. It would be one thing if we were caching a specific software application where there were lots of knowns. That's exactly the opposite with WordPress though. When you write a plugin for WordPress there are more unknowns than anything else; i.e., you can never know for sure what theme/plugins are going to be mixed together, and what the PHP code in those will actually do.

**Comment by raamdev** [comment]
> I think that any POST request (or any uncacheable request type, for that matter) should trigger a full wipe of the cache for that user. Caching logged-in users is already an oxymoron so-to-speak. With this feature, we are pushing the limits of what a page cache can do. Trying to preserve the cache even after we know that a user POSTd something to the server seems like it is asking for trouble.

I agree. I don't think we need to change anything here. I am, however, going to write a KB Article that explains why the user cache is cleared whenever a user logs in. I'll also include the reasoning you explained above. Thanks for the thorough explanation! :-)

**Comment by erikture** [comment]
As I have asked for refund of my money because the plugin does not meet my needs I do not really care any  more, but this is how I would like it to work:
I do not think that it should be that hard to implement eighter, as you alreade have the functionallity. It is just about when to clear the cache.

My site is a site showing my cottage for persons that might whant to rent it or persons that will rent/visit it. I do not whant it to be a public site because only family and frends are allowed to rent it. I also would like to show different content to persons thinking of renting it and persons actually going to visit the cottage.

There for I have user named guest and user named visitor. These users are not physical persons. Every person that are thinking of renting it is given the guest user name and password so that they can read about the cottage. Once they have made a reservation they get the visitor username and passoword.

Depending on which user that loggs in different pages are shown. There are no user interaction involved except for reading pages and posts.

I would like the cache to work very much the same as most of the common Wordpress plugins available for public sites. The cache remains intact until a page/post is created, updated or deletet or until some specified time has expired or the admin manually clears the cache. No other cases will clear the cache. The difference between other plugins and ZenCache is that ZenCache can handle different versions of the same page, ie one for each user.

This could be configured in the plugin gui with a fourth way of handling logged in users.

**Comment by raamdev** [comment]
Referencing draft for related KB Article: https://github.com/websharks/comet-cache-kb/issues/105
