### ISSUE TITLE
Adding support for phpFastCache

### ISSUE THREAD

**Issue by tobias86aa** [wpsharks/comet-cache#485]
Hi

This sounds like something good: http://www.phpfastcache.com/ II https://github.com/khoaofgod/phpfastcache

Could this be something that could be added?

**Comment by raamdev** [comment]
phpFastCache is for PHP Object Caching, which we have chosen not to do in ZenCache because object caching is very prone to causing problems with other WordPress plugins, i.e., other plugins must be written with object caching in mind to work properly and many are not. That's why when it comes to WordPress and object caching, it's best to implement object caching as part of a bigger overall deployment strategy where each plugin you're running has been specifically optimized (or at least reviewed) for object caching. 

Another reason we've chosen not to focus on object caching at this time is that object caching in WordPress would save you database queries, however when you're running a page caching plugin like ZenCache, there are no database queries happening at all when ZenCache serves a cached page. Also, the WordPress Core is already very optimized and includes a lot of built-in object caching, further reducing the need for adding this to a plugin.

phpFastCache itself is not designed to run with something like WordPress, but rather is designed to be added to a PHP project that you may be working on so that you can make use of object caching without writing such a library from scratch.
