### ISSUE TITLE
Feature Request: Option to reset Opcode cache when clearing the cache

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#489]
Forked from https://github.com/websharks/zencache/issues/342#issuecomment-106897489.

The new PHP 5.5+ Opcache extension allows resetting the Opcode cache via [`opcache_reset()`](http://php.net/manual/en/function.opcache-reset.php). ZenCache should have a new option panel called "Opcode Cache" that includes a button to manually reset the Opcode cache, along with an option to disable automatic Opcode cache resetting whenever the ZenCache cache is cleared (the default would be enabled). 

This panel can also include a PHP code snippet and reference to the "Process Other Custom PHP Code?" section inside **ZenCache → Plugin Options → Clearing the Cache** in case the site owner wants more advanced control over this functionality.

**Comment by isaumya** [comment]
:+1:

**Comment by jaswrks** [comment]
:+1:

**Comment by raamdev** [comment]
@jaswsinc The new "Clear the OPCache Too?" option is located in the new "Manual Cache Clearing" section of the options, which I assume means that it applies only to the "Clear Cache" button, not to any automatic cache clearing routines (there's no corresponding option inside the new "Automatic Cache Clearing" section as I would've expected).

Can you confirm if this was intentional or if you just overlooked it?

![2015-09-17_22-16-43](https://cloud.githubusercontent.com/assets/53005/9950578/127000ea-5d8a-11e5-8bcd-a60164a8bf43.png)

**Comment by jaswrks** [comment]
The OpCache is only cleared in the following circumstances:
- If enabled in the manual section, and you clear the cache manually.
- If enabled in the manual section, and ZenCache clears the **entire** cache manually and/or automatically. This occurs rarely. Generally speaking, it occurs only when you change the plugin options and/or an upgrade of the software occurs.

I don't think the OpCache should ever be cleared in an automatic way otherwise, because the OpCache really only needs to be cleared whenever filesystem changes occur; i.e., when ZenCache options change and the `advanced-cache.php` file is rewritten, or when a site owner clears the entire cache and they want to know that _everything_ is being cleared.

**Comment by raamdev** [comment]
@jaswsinc Thanks for the clarification! :-)

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **New Feature!** When your server has the [PHP OPCache Extension](http://zencache.com/r/php-opcache/) installed, ZenCache can now be configured to also clear the PHP opcode cache whenever you clear the cache manually using the ZenCache "Clear Cache" button. See _ZenCache Options → Manual Cache Clearing → Clear the PHP OPCache Too?_ (note that this option only appears if you have the OPCache Extension installed). Props @jaswsinc. See [Issue #489](https://github.com/websharks/zencache/issues/489).

**Comment by raamdev** [comment]
**ZenCache Pro v151002** has been released and includes changes from this GitHub Issue. 

See the [ZenCache Pro v151002 release announcement](http://zencache.com/zencache-pro-v151002-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#489).
