### ISSUE TITLE
3rd Party Plugin Compatibility: Really Simple CAPTCHA

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#499]
See: https://wordpress.org/plugins/really-simple-captcha/

This plugin has over 1 million active installs and is often used in conjunction with Contact Form 7 (see #500).

There have been some reports of issues between ZenCache and Really Simple CAPTCHA and it would be nice if ZenCache worked seamlessly (or at least provided the necessary Dashboard messaging to ensure smooth operation).

---
### Support threads referencing this issue
- https://wordpress.org/support/topic/captcha-not-working-in-the-contact-form-7-while-the-cache-is-enabled
- https://wordpress.org/support/topic/zencache-not-playing-nicely-with-contact7
- https://wordpress.org/support/topic/missing-captcha-image-2?replies=2
- https://wordpress.org/support/topic/captcha-is-getting-cached?replies=2

**Comment by DecimusBurton** [comment]
Any updates.  See there is a new update for zencache Version 150626.  This has still not fixed the new problem of the Really Simple CAPTCHA image caching and getting out of synch with the input thus causing a verification error.

Unfortunately I've had to disable zencache again.  Booo Hoo!  Missing zencache

**Comment by raamdev** [comment]
@DecimusBurton Our development window for v150626 had already closed by the time this GitHub Issue was opened. Now that we're starting a new cycle, we'll see if we can add this to the next release. :-)

**Comment by DecimusBurton** [comment]
Keen to get zencache working again and happy to help.  Even hapoyvto give
you access to site if you want to nose around

Peter

Peter Burton
sent from phone

**Comment by DecimusBurton** [comment]
any news on a fix for ZenCache with Contact7 combined with

_Really Simple CAPTCHA_

_I've jsut set up a new website and as soon as I turn on zencache the
Captcha image caches and does not change.  WIll have to look for an
alternative for zencache.  Have always used it as it was the recommendation
of the weaver template I tend to use._

_Peter_

On 29 June 2015 at 16:56, Raam Dev notifications@github.com wrote:

> @DecimusBurton https://github.com/DecimusBurton Our development window
> for v150626 had already closed by the time this GitHub Issue was opened.
> Now that we're starting a new cycle, we'll see if we can add this to the
> next release. :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/websharks/zencache/issues/499#issuecomment-116740579.

## 

Peter E Burton 巴培德
e-mail: peter.burton@decimus.com
UK mobile: +44 (0)787 261-0026
UK home: +44 (0)1372 451-706

## HK mobile: +852 9315-1181

## skype: decimus_burton

UK address:  Ranmore, Beech Avenue, Effingham, Near Leatherhead, Surrey

## KT24 5PJ, UK

Email Disclaimer: The information in this email is confidential and may be
legally privileged. It is intended solely for the addressee.

**Comment by jaswrks** [comment]
## Short-Term Workaround

Add `_wpcf7_is_ajax_call` to your list of ZenCache URI Exclusions.

## Possible Long-Term Solution

The Contact Form 7 developer might want to consider using `DONOTCACHEPAGE` in their AJAX handler in order to prevent WordPress caching plugins from caching the response that is dynamic. Referencing: https://github.com/wp-plugins/contact-form-7/blob/master/includes/controller.php

See also: https://github.com/websharks/zencache-kb/issues/47

**Comment by DecimusBurton** [comment]
many thanks.  appreciate help.  the work around works

On 11 July 2015 at 00:56, JasWSInc notifications@github.com wrote:

> Short-Term Workaround
> 
> Add _wpcf7_is_ajax_call to your list of ZenCache URI Exclusions.
> Possible Long-Term Solutions
> 
> The Contact Form 7 developer might want to consider using DONOTCACHEPAGE
> in their AJAX handler in order to prevent WordPress caching plugins from
> caching the response that is dynamic. Referencing:
> https://github.com/wp-plugins/contact-form-7/blob/master/includes/controller.php
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/websharks/zencache/issues/499#issuecomment-120552654.

## 

Peter E Burton 巴培德
e-mail: peter.burton@decimus.com
UK mobile: +44 (0)787 261-0026
UK home: +44 (0)1372 451-706

## HK mobile: +852 9315-1181

## skype: decimus_burton

UK address:  Ranmore, Beech Avenue, Effingham, Near Leatherhead, Surrey

## KT24 5PJ, UK

Email Disclaimer: The information in this email is confidential and may be
legally privileged. It is intended solely for the addressee.

**Comment by DecimusBurton** [comment]
Short-Term Workaround
Add _wpcf7_is_ajax_call to your list of ZenCache URI Exclusions.

Jumped the gun!
Cannot get it to work.  Something really odd is happening.  If I add the above to the URI Exclusions.  Even if I add _wpcf7_captcha_challenge_captcha it works ONLY while I am logged into the /wp-admin/ page.  Typically what I was doign to test is open the actual page in a separate tab.  I can go to the contact page, press reload and the captcha image refreshes.  

Exit the /wp-admin/  and then go to the contact page, press refresh and the captcha image stays ie its cached.  

I've gone back in and disabled zen cache from all my sites again!

I'll act as postman and post your longterm solution to the Contact7 support page

**Comment by DecimusBurton** [comment]
Acting as messenger.  Please see 
https://wordpress.org/support/topic/captcha-cache-issue?replies=4

The feedback from the Contact7 Form author was

Do you have this line in your wp-config.php file?
`
define('WP_CACHE', TRUE);
`
I checked 12 wp-config files and only two old/ test sites have
`
<?php
define('WP_CACHE', TRUE);
`

The feedback was:
Normally ZenCache should have added it. Ask ZenCache author for support. 

Do I need to go into each of my wp-config files and add that at the start?

**Comment by DecimusBurton** [comment]
I just ran a test on http://www.bajanthings.com/contact-burts/

Adding in
`
<?php
define('WP_CACHE', TRUE);
`
as the second line of the wp-config does not solve the caching of the CAPTCHA image on page refresh

So I have now removed it as the second line and agan disabled zencache.

Peter

**Comment by raamdev** [comment]
> Do I need to go into each of my wp-config files and add that at the start?

@DecimusBurton The `define('WP_CACHE', TRUE);` line _is_ added automatically by ZenCache when you enable caching in **ZenCache → Plugin Options → Enable/Disable** and automatically removed from `wp-config.php` when you deactivate the ZenCache plugin. That line simply tells WordPress that a caching plugin is installed and should be used.

If the Really Simple CAPTCHA plugin is still not preventing caching on pages where the CAPTCHA is present, then the plugin developer is not properly setting `define(DONOTCACHEPAGE, TRUE);` on those pages. The Really Simple CAPTCHA plugin author should be setting that `DONOTCACHEPAGE` constant to `TRUE` on any pages where Really Simple CAPTCHA is being loaded, so that the CAPTCHA does not get cached.

**Comment by DecimusBurton** [comment]
I might have a fix on this.  I think this might be a FireFox issue.  See below
I have enabled ZenCache on BajanThings.  (BTW I see define('WP_CACHE', TRUE); is now on line 2 of wp-config.php)  The only thing I have changed from the default setting is the cache time, which I have changed from 7 days to 2 hours.

Go to: http://www.bajanthings.com/contact-burts/
- Open it in IE, I am using Version 11.0.9600.17842, 
  press page reload and the CAPTCHA image refreshes as expected.
- Open it in Chrome, I am using Version 43.0.2357.132 m, 
  press page reload and the CAPTCHA image refreshes as expected.
- Open it in Firefox, I am using Version 39.0, 
  press page reload and the CAPTCHA image DOES NOT refreshes as expected.
  Are you seeing this too?

**Comment by raamdev** [comment]
@DecimusBurton I just tested that page in the following browsers on my Mac (OS X 10.10), refreshing the page to see if the CAPTCHA changes with each page refresh:
- Firefox v38.0.5 (works)
- Chrome v43.0.2357 (works)
- Safari v8.0.7 (works)

**Comment by DecimusBurton** [comment]
Ummm.  I just tried again on a freshly rebooted machine.  Exact same results as before.  Chrome  and IE refresh the CAPTCHA.  Firefox doesn't.  I am using win 8.1 64 bit in case that makes any difference.

**Comment by jaswrks** [comment]
> Open it in Firefox, I am using Version 39.0, press page reload and the CAPTCHA image DOES NOT refreshes as expected. Are you seeing this too?

I was unable to reproduce this, and given what I investigated in the source code this is not something that will be browser-dependent. The AJAX response is either cached "server-side" or it's not. No matter the browser. I suspect what you're seeing could be attributed to a local browser cache in Firefox. Be sure to clear your browser temp/cache files before retesting this.

If that resolves the issue, you could also ask the Contact Form 7 developer to be sure that `nocache_headers()` in the WordPress core is called on AJAX requests that produce dynamic content.

---

@raamdev I see nothing ZenCache-specific here. This really seems to be two issues with CF7.
- Not setting `DONOTCACHEPAGE` on AJAX responses that deliver dynamic content.
- Not calling `nocache_headers()` on AJAX responses that deliver dynamic content.

_Those are both educated guesses. I have not spent enough time with that plugin to say absolutely for sure. Further investigation on their part would be suggested._

**Comment by DecimusBurton** [comment]
Thanks guys.  I will repost tonight and re-test with a cleared cache which
I thought I had done as I am aware Firefox is a bit more aggressive here.

On 14 July 2015 at 08:09, JasWSInc notifications@github.com wrote:

> Open it in Firefox, I am using Version 39.0, press page reload and the
> CAPTCHA image DOES NOT refreshes as expected. Are you seeing this too?
> 
> I was unable to reproduce this, and given what I investigated in the
> source code this is not something that will be browser-dependent. The AJAX
> response is either cached "server-side" or it's not. No matter the browser.
> I suspect what you're seeing could be attributed to a local browser cache
> in Firefox. Be sure to clear your browser temp/cache files before retesting
> this.
> 
> If that resolves the issue, you could also ask the Contact Form 7
> developer to be sure that nocache_headers() in the WordPress core is
> 
> ## called on AJAX requests that produce dynamic content.
> 
> @raamdev https://github.com/raamdev I see nothing ZenCache-specific
> here. This really seems to be two issues with CF7.
> - Not setting DONOTCACHEPAGE on AJAX responses that deliver dynamic
>   content.
> - Not calling nocache_headers() on AJAX responses that deliver dynamic
>   content.
> 
> _Those are both educated guesses. I have not spent enough time with that
> plugin to say absolutely for sure. Further investigation on their part
> would be suggested._
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/websharks/zencache/issues/499#issuecomment-121149375.

## 

Peter E Burton 巴培德
e-mail: peter.burton@decimus.com
UK mobile: +44 (0)787 261-0026
UK home: +44 (0)1372 451-706

## HK mobile: +852 9315-1181

## skype: decimus_burton

UK address:  Ranmore, Beech Avenue, Effingham, Near Leatherhead, Surrey

## KT24 5PJ, UK

Email Disclaimer: The information in this email is confidential and may be
legally privileged. It is intended solely for the addressee.

**Comment by DecimusBurton** [comment]
Keeping you in loop.

Looks as if issue is WP PHOTON.  Am awaiting to hear back.  Support link is below

https://wordpress.org/support/topic/captcha-cache-issue?replies=4

**Comment by raamdev** [comment]
> Keeping you in loop.

@DecimusBurton Thanks for keeping us in the loop! :-)

**Comment by renzms** [comment]
@raamdev 

## Unable to reproduce with Really Simple CAPTCHA


The Really Simple CAPTCHA plugin itself seems bugged at the moment and does not appear on any form properly even in a clean installation.

Please refer to notes below and testing for Contact Form 7 + Really Simple CAPTCHA/reCAPTCHA and [issue 500](https://github.com/websharks/comet-cache/issues/500)


### Tested with 

 - WordPress 4.6.1
 - Comet Cache™ Pro v161119
 - Contact Form 7 Version 4.5.1
  + Really Simple CAPTCHA and reCAPTCHA

Please also note Really Simple Captcha is out of date and hasn't had official support in 7 months nor is it compatible with the latest version of **WordPress 4.6.1**. It has only been tested up to **WordPress 4.3.1**.

From Contact Form 7 Page:

>Really Simple CAPTCHA
[Edit: 2015-09-17] Contact Form 7 4.3 and later recommend reCAPTCHA instead of Really Simple CAPTCHA. For more details, see Contact Form 7 4.3.

>Contact Form 7 allows you to insert a CAPTCHA into your contact form to prevent bots from submitting forms. Contact Form 7 utilizes Really Simple CAPTCHA as its officially-sanctioned CAPTCHA module, so you will need to install the Really Simple CAPTCHA plugin before you use CAPTCHA in your form.

From [WordPress Plugin Page](https://wordpress.org/plugins/really-simple-captcha/)

 - Really Simple Captcha Version 1.9 **Last Updated: 7 months  Untested with your version of WordPress - 4.6.1**

>Really Simple CAPTCHA does not work alone and is intended to work with other plugins. It is originally created for Contact Form 7, however, you can use it with your own plugin.

>Note: This product is "really simple" as its name suggests, i.e., it is not strongly secure. If you need perfect security, you should try other solutions.

The [new default captcha for Contact form 7 is reCaptcha](http://contactform7.com/recaptcha/)

>On Contact Form 7 4.3 and greater, reCAPTCHA is the standard CAPTCHA solution.

>Don’t confuse reCAPTCHA with Really Simple CAPTCHA, which was the default CAPTCHA solution prior to 4.3. Really Simple CAPTCHA is a WordPress plugin I’ve created and maintained for 8 years. reCAPTCHA is Google’s service, and has tremendous advantages over Really Simple CAPTCHA.


## Unable to reproduce with reCAPTCHA

### Testing with reCAPTCHA

reCAPTCHA uses a different way of verifying with a checkbox and validation through Javascript prompts.

reCAPTCHA Checkbox:
- ![screen shot 2016-11-23 at 11 59 29 pm](https://cloud.githubusercontent.com/assets/13220018/20568992/752d0c24-b1d9-11e6-8fbe-be72c46eef67.png)

reCAPTCHA Checked:
- ![screen shot 2016-11-23 at 11 59 16 pm](https://cloud.githubusercontent.com/assets/13220018/20569005/80859726-b1d9-11e6-9696-8f84ed2401a0.png)

Verification Pop Up:
- ![screen shot 2016-11-23 at 11 59 01 pm](https://cloud.githubusercontent.com/assets/13220018/20569017/8cfd09f8-b1d9-11e6-852b-e1916578f158.png)

Upon a second visit the verification Pop Up has changed:
- ![screen shot 2016-11-23 at 11 59 35 pm](https://cloud.githubusercontent.com/assets/13220018/20569104/d6193350-b1d9-11e6-9630-a6aa95691f27.png)


The page itself with the form is not cached due to the presence of `_wpnonce`, but for the purpose of this test I also tried with nonce caching enabled for logged-in users.

- ![screen shot 2016-11-23 at 11 43 28 pm](https://cloud.githubusercontent.com/assets/13220018/20569738/1d938080-b1dc-11e6-868e-3727b5382faf.png)


### Observed Behavior with nonce caching enabled for logged-in users

The page itself is cached but the reCAPTCHA check box is not cached to allow verification:

- ![screen shot 2016-11-23 at 11 44 33 pm](https://cloud.githubusercontent.com/assets/13220018/20569154/1095defc-b1da-11e6-9ad9-ea267df6330b.png)

- ![screen shot 2016-11-23 at 11 59 29 pm](https://cloud.githubusercontent.com/assets/13220018/20569160/1338c106-b1da-11e6-9096-28ec24442309.png)


Please note though that after checking the box, no javascript verification pops up for the logged in user and proceeds with the checkbox being verified:

- ![screen shot 2016-11-23 at 11 59 16 pm](https://cloud.githubusercontent.com/assets/13220018/20569359/cc233a0c-b1da-11e6-8eda-1f5925c2f3c4.png)


### Conclusion
reCAPTCHA does not have any major issues with Comet Cache Pro

However, the Contact Form 7 plugin does have compatibility issues with Comet Cache Pro noted in the testing here: https://github.com/websharks/comet-cache/issues/500#issuecomment-262560189
