### ISSUE TITLE
3rd Party Plugin Compatibility: Contact Form 7

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#500]
See: https://wordpress.org/plugins/contact-form-7/

This plugin has over 1 million active installs and is often used in conjunction with Really Simple CAPTCHA (see #499).

There have been some reports of issues between ZenCache and Contact Form 7 and it would be nice if ZenCache worked seamlessly (or at least provided the necessary Dashboard messaging to ensure smooth operation).

---
### Support threads referencing this issue
- https://wordpress.org/support/topic/captcha-not-working-in-the-contact-form-7-while-the-cache-is-enabled
- https://wordpress.org/support/topic/zencache-not-playing-nicely-with-contact7
- https://wordpress.org/support/topic/missing-captcha-image-2?replies=2
- https://wordpress.org/support/topic/captcha-is-getting-cached?replies=2
- https://wordpress.org/support/topic/comet-cache-not-caching-pages-because-of-contact-form-7-nonce/

**Comment by jaswrks** [comment]
I tested this a while back...

## Problems

Contact Form 7 lacks a cache-friendly design. The author of this plugin has not implemented `DONOTCACHEPAGE` when appropriate.

## Short-Term Workaround

Add `_wpcf7_is_ajax_call` to your list of ZenCache URI Exclusions.

## Possible Long-Term Solution

The Contact Form 7 developer might want to consider using `DONOTCACHEPAGE` in their AJAX handler in order to prevent WordPress caching plugins from caching the response that is dynamic. Referencing: https://github.com/wp-plugins/contact-form-7/blob/master/includes/controller.php

See also: https://github.com/websharks/zencache-kb/issues/47

**Comment by renzms** [comment]
@raamdev 

### Bug Confirmed when `_wpnonce` Caching is enabled for logged-in users


### Tested with 

 - WordPress 4.6.1
 - Comet Cache™ Pro v161119 with `_wpnonce` Caching enabled for logged-in users
 - Contact Form 7 Version 4.5.1 + reCAPTCHA

### Observed Behavior with logged-out users

The page itself with the form is not cached due to the presence of `_wpnonce`

![screen shot 2016-11-23 at 11 43 28 pm](https://cloud.githubusercontent.com/assets/13220018/20569492/397470da-b1db-11e6-9be3-d723337d4a29.png)



### Observed Behavior with nonce caching enabled for logged-in users

The page with the form is cached and does not update even with **Auto Cache Clearing Enabled**. When options on the form change or are removed (e.g, a field is removed/updated, field name change) the form remains the same for the logged-in user. The form only updates when cache is manually cleared.

![screen shot 2016-11-23 at 11 44 33 pm](https://cloud.githubusercontent.com/assets/13220018/20569561/76e250cc-b1db-11e6-8cbe-0ac958b970d9.png)

**Comment by raamdev** [comment]
@renzms Thank you. 

So to reiterate, here's what needs to happen to improve compatibility with Contact Form 7 at this point:

- When a change is made to a form in Contact Form 7, the cache for any pages showing the form needs to be cleared (namely the logged-in user cache, since the presence of a `nonce` in the page source prevents caching otherwise).

I'm not sure if this is even going to be possible. I believe Contact Form 7 just provides a shortcode that you place on a Post/Page to show the form. If that's the case, then there might not be any way to know which Posts/Pages contain a Contact Form 7 shortcode without somehow going through all of the page content in WordPress looking for the shortcode (not an option given the high workload of such a task).

A better workaround would be for the site owner to use the Comet Cache URI Exclusion patterns to exclude any pages that contain Contact Form 7 shortcodes from be cached, or if they prefer to cache the form for logged-in users, they should remember to manually clear the cache for that page after making any changes to the form on that page.

I'm going to close this for now, as I'm not seeing anything actionable that we can do here.
