### ISSUE TITLE
CDN cache buster iv counter not increased after Clear Cache button?

### ISSUE THREAD

**Issue by lkraav** [wpsharks/comet-cache#521]
I think I'm seeing this on a site. Old static assets are being downloaded from CDN with no easy way to refresh them. Looking at network panel, after hitting Clear Cache, still the same `iv` request parameter is used. Where is the `iv` variable value displayed at the ZenCache panel so I could verify it? Should it increase +1 every time Clear Cache is pressed?

**Comment by raamdev** [comment]
@lkraav That is currently the expected behavior, i.e., the `iv` attribute only increments on a few major events, such as when WordPress is upgraded. We recognize the need to be able to "clear" the CDN cache by manually incrementing the `iv` attribute, and we have a feature request open for that here: #488 

I recommend leaving a comment on that feature request to show your support for that feature. I'll go ahead and close this issue in favor of #488.
