### ISSUE TITLE
Cached homepage with PHP fatal error

### ISSUE THREAD

**Issue by allklier** [wpsharks/comet-cache#523]
Version 150409

Cached homepage with error message 'Fatal error: execution time of 30s exceeded'. 

Visiting homepage always showed this message immediately due to caching.

Presumably error filter didn't catch that this wasn't a good page? After clearing cache everything back to normal.

Possible ways to reproduce: change php.ini to set short execution limit (e.g. 2s) and then hit .php page that runs in infinite loop until it is killed.

**Comment by raamdev** [comment]
@allklier Thanks for the report. Can you tell me which version of PHP you're running?

@jaswsinc Any thoughts on this?

**Comment by jaswrks** [comment]
@raamdev writes...

> @jaswsinc Any thoughts on this?

cc @allklier 

> Possible ways to reproduce: change php.ini to set short execution limit (e.g. 2s) and then hit .php page that runs in infinite loop until it is killed.

We will need more information I'm afraid. I was unable to reproduce in a clean installation. This may or may not have anything to do with ZenCache. In order for us to know for sure, we need to know which line of code triggers this timeout, and what other plugins you're running together with ZenCache; along with the theme that you're currently using.

Even then, any help you can offer in terms of finding the line of code that creates an infinite loop would be helpful. My feeling is that this is most likely an output buffer conflict with another plugin, but very difficult to know for sure unless and until we have an environment that exactly matches.

**Comment by allklier** [comment]
We had two separate line numbers where the error occurred: 

wp-includes/options.php, line 0
wp-includes/functions.php, line 288

PHP Version 5.4.41

Plugins on site are:

Akismet 3.1.3
Aweber Forms 1.1.15
BackupBuddy 5.2.0.9
Custom Login 3.2.3
Disqus 2.84
EventOn 2.2.9
iThemes Security 4.8.0
Regenerate Thumbnails 2.2.4
Store Pickup 2.1.0
Twitter Cards 1.0.5
WooCommerce 2.3.13
Wordpress SEO 2.2.1
YITH WooCommerce Magnifier 1.0.0
ZenCache Pro 150409

**Comment by jaswrks** [comment]
> wp-includes/options.php, line 0
> wp-includes/functions.php, line 288

Thank you. Which version of WordPress is this?

**Comment by allklier** [comment]
Wordpress 4.2.2

**Comment by jaswrks** [comment]
> wp-includes/options.php, line 0
> wp-includes/functions.php, line 288
> Wordpress 4.2.2

![2015-07-10_19-00-45](https://cloud.githubusercontent.com/assets/1563559/8632058/ea41d8d4-2736-11e5-8b44-33ae31ff218f.png)

Thank you. Hmm, neither of these line numbers seem to make sense in terms of there being an infinite loop. So my assumption is that this is caused by another routine that is simply making calls to various portions of the WordPress core. Thus, you end up with odd line numbers in the error.

So here's what we know thus far...
- Does not occur in a clean installation.
- Does occur with a specific combination of plugins.
- Error is reported at various line numbers; i.e., nothing specific yet.

Since some of your plugins are commercial; i.e., difficult for others to acquire and test against easily, my suggestion is that you disable one other plugin at a time until you can narrow this down to a specific ZenCache + [mystery plugin or theme] that triggers this.

I understand that, at the moment, disabling ZenCache resolves the issue. However, ZenCache by itself doesn't result in this behavior. So there is another wildcard that we need to narrow this down to. If you find that disabling any other plugin dodges this bug, we can look to see if there is a way to work around that conflict, and hopefully determine what the conflict actually consists of.

**Comment by allklier** [comment]
Makes sense. 

This site has existed in this configuration for quite some time. But the bug showed up the same day several plugins were updated as part of our monthly maintenance. That may narrow down the plugins to suspect. The other thing that happened the same day of the error is an update to cPanel from 1.48 to 1.50 which failed and had to be re-run. Since this is a live commercial site it may be challenging to disable plugins long enough to see if the bug re-appears, but I will attempt to narrow down the list of candidates.

**Comment by allklier** [comment]
The plugins that were updated within 24 hours of the failure are:

Akismet 3.1.3
WooCommerce 2.3.13
Wordpress SEO 2.2.1

Akismet is fairly lightweight, so the suspicion would be on the other two.

Nothing on the site (or the homepage in particular) is particularly slow though. So a 30s load time is quite uncommon. I would assume that it was another server load factor that delayed the page load sufficiently to trigger the timeout.

One odd parameter about this site is, that for historical reasons it's located in a wordpress sub-folder with a index.php and .htaccess in the webroot. Now again, this has been the case for a long time though.

**Comment by allklier** [comment]
Are there any server logs that may be able to shed some lights? This is running on a VPS server, so I have shell access and root privileges to access any log that may shed light.

**Comment by jaswrks** [comment]
> Nothing on the site (or the homepage in particular) is particularly slow though. So a 30s load time is quite uncommon. I would assume that it was another server load factor that delayed the page load sufficiently to trigger the timeout.

My guess, just a guess, is that this is caused by a rogue sub-routine in one of your other plugins. As you said, there is very little reason for _any_ script to take more than 30 seconds. In fact, it would be abnormal for any plugin to run a routine that takes more than .5 seconds.

However, if you have a scenario taking place in the code that creates an infinite loop, the script could run forever, theoretically. This is why there is a timeout in PHP; i.e., to stop infinite loops that would otherwise run forever in duplicate until it crashes your server.

So what I'd suggest is that you inspect server error logs, disable plugins one at a time, and perhaps even setup a staging server where you can work to hunt down the conflicting combination.

> Are there any server logs that may be able to shed some lights? This is running on a VPS server, so I have shell access and root privileges to access any log that may shed light.

Yes. You should have both a web server error log and also a PHP error log. Assuming that you have PHP error reporting on, and that your `php.ini` file is configured to log errors.

**Comment by allklier** [comment]
That all makes sense. But the key question for me is that the error handler in PHP is a built-in routine and should always behave the same, regardless of plugins and other details. The only difference may be whether any output or headers have been sent by the time it triggers or not. 

I'm not familiar with your plugin architecture, but it seems that there are two opportunities to prevent caching an error page. One is by catching the server error as it occurs. The other one is by looking at the content of the cached page before using it.

You are right that there is probably something off in one of the plugins. And I went through the logs and found that the timeout occurred on a number of different routines and line number, and indication that the page is running slow but not stuck. It just depends on the timing when the 30s are up.

I can't disable plugins on this site for long periods of time and experiment. This site is now running on a different server than when the ZenCache was originally added. So I'm tempted to just keep it disabled. If there are other ways to find out what happened or safe guard against caching an error page, I'm happy to give it another try.

**Comment by allklier** [comment]
One final piece of interest from the logs: In the two days leading up to the site failure I can see a total of 26 occurrences of the error '30 second timeout'. Ever since clearing the cache and turning it off, the site has been running fine and no more timeouts have occurred. Those were the only changes we made during site recovery.

It may in fact be, that the cache contributed to the slowness of the site.

One tidbit is that we moved the site not too long ago from a different server (within the 7 day cache retention window). We usually use ImportBuddy as our migration script which deals with both the files and database and any adjustments in a single script. I'm pretty certain that this script would have copied the cache folders across from the old server. I don't know if there is anything in the plugin logic that may get tripped if it were to find cache files that were written on a different server, possibly with different versions of PHP and Apache?

**Comment by raamdev** [comment]
We have still been unable to reproduce the issue described here and we haven't received any other reports like this, so I'm going to close this issue as `cannot reproduce`. 

@allklier If you're able to reproduce this issue in a [Clean WordPress Installation](http://zencache.com/kb-article/testing-zencache-in-a-clean-wordpress-installation/), please update this issue and we'll take a closer look.
