### ISSUE TITLE
Creation of a 'ghost' file when doing html css js compression

### ISSUE THREAD

**Issue by tinteo** [wpsharks/comet-cache#525]
Hi , using zencache pro Version 150626 

When I activated the html compression, I get several useful files + one that does not exist and is requested from zencache. Desactivating and reactivating the plugin, makes a second "ghost" file. 
See here: in the requests. 
http://tools.pingdom.com/fpt/#!/cjMVzw/http://www.tinteo.com/

**Comment by raamdev** [comment]
@tinteo I have not been able to reproduce this.

Can you please try disabling caching (**ZenCache → Plugin Options → Enable/Disable**) and then re-enabling it? 

Also, you could try clicking the "Restore" button at the top of the plugin options page (**ZenCache → Plugin Options**); if you have any custom settings please back them up first using **s2Member → Import / Export** so that you can restore them after clicking the "Restore" button. 

Finally, if none of the above work, I would try deactivating ZenCache, manually deleting the ZenCache cache directory: `wp-content/cache/zencache/`, then reactivating ZenCache.

It sounds to me like you have a cache file that is pointing to an old compressed CSS/JS file, which would only happen if for some reason ZenCache has not been able to properly clear your cache.

**Comment by tinteo** [comment]
The plugin update fixed the problem.

**Comment by raamdev** [comment]
@tinteo Awesome. Thanks for the update! :-)
