### ISSUE TITLE
Feature Request: Option to Include License Key in Export/Import Process

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#529]
Feature requested by _ZenCache_ user to have the already built-in **Export/Import** feature also include the **License Key** in the transfer of data/settings.

This would save time in _copy/pasting_ the **License Key** on each install of **ZenCache Pro**.

Please see original ticket for request here and update once feature is added:
https://websharks.zendesk.com/agent/tickets/7426

**Comment by raamdev** [comment]
@renzms Thanks for submitting this feature request.

---

It's important to note that **this should be optional**, not a default. There should be a checkbox on the Export page that allows a site owner to _include_ the License Key in the export if they want to do that.

Also, obviously, if the site owner is using their password instead of the license key in the Pro Updater, we probably shouldn't allow that to be included in the Export file (unless we can safely do that? I assume its stored encrypted).

**Comment by rtrevellyan** [comment]
This feature would be very useful for me when setting up a new install of ZenCache Pro. Making the license key an optional part of either export or import makes sense to me. I would prefer to have the option on import rather than export. That way I could import the same settings to more sites with less effort.

**Comment by jaswrks** [comment]
> to have the already built-in Export/Import feature also include the License Key in the transfer of data/settings.

Just wanted to note that this is already the case. The License Key (or password) is already included in the options export file by default, and this is already imported by ZenCache Pro as well. I just tested/confirmed this to be the case in ZenCache Pro v150716.

> It's important to note that this should be optional, not a default. There should be a checkbox on the Export page that allows a site owner to include the License Key in the export if they want to do that.

This is not possible yet; i.e., it's just included in the export/import by default.

> probably shouldn't allow that to be included in the Export file (unless we can safely do that? I assume its stored encrypted).

It is not encrypted.

**Comment by rtrevellyan** [comment]
Then I must have made a mistake somewhere along the way. Sorry for wasting time.

**Comment by raamdev** [comment]
> Just wanted to note that this is already the case.

Confirmed. I just tested this myself and I see the License Key is included when exporting the options.
