### ISSUE TITLE
Captcha is getting cached

### ISSUE THREAD

**Issue by pankajsingh210** [wpsharks/comet-cache#550]
I'm using "Really simple captcha" plugin and it is getting cached everytime. I had to clear the cache or disable the cache in order to make capctha work properly.

Please tell me a way to avoid caching of captcha plugin.

**Comment by pankajsingh210** [comment]
I think I have found the solution.  I wanted to avoid the page from getting cached. So I did it by checking all those page manually on content.php inside theme folder with there id  as follows -

```
<?php 
        $categoryId = $post_category[0]->cat_ID;
        if ((is_single() && (($categoryId == 31) || ($categoryId == 32))) || (is_page(2784)) || (is_page(3621)) || (is_page(3544))) { 
                function clear_cache_for_page_id_5( ) {
                    $GLOBALS['zencache']->auto_clear_post_cache($post_category[0]->object_id);
                }
        }
?>
```

Here I have called out predefined function of ZenCache to clear cache for that particular page.

**Comment by jaswrks** [comment]
@pankajsingh210 Here are some options for you.
- Contact the author of this plugin and ask them to read over this article so they can make that plugin cache friendly. See: https://github.com/websharks/zencache-kb/issues/47
- Or, use the details in the same article and set the `DONOTCACHEPAGE` constant yourself. Perhaps using the code that you posted above. Instead of clearing the cache on every pageview, which is very expensive in terms of resource usage; you should simply tell ZenCache to exclude that page from the cache, because it contains dynamic content. See: https://github.com/websharks/zencache-kb/issues/47

**Comment by pankajsingh210** [comment]
@jaswsinc -- Thank you so much for taking out time to reply on this thread.  The above code which I used seemed working once. But it failed again. Because the page itself get cached and the code is not executed from the second time. 
In my theme, **content.php** is used for many different pages and post. So there are few posts and page on which I have form, which I don't want be cached.

So how can I use your given flag dynamically for those pages and posts.

**Comment by raamdev** [comment]
@pankajsingh210 We have a feature request open to look into compatibility with the Really Simple Captcha plugin: https://github.com/websharks/zencache/issues/499 I suggest leaving a comment and any feedback regarding that plugin over in that GitHub issue.

If you want to exclude a specific page from being cached by ZenCache, simply add that pages URI to **ZenCache → Plugin Options → URI Exclusion Patterns** and ZenCache will not cache that page.

I'm going to close this issue in favor of #499.
