### ISSUE TITLE
Support for Fastly CDN

### ISSUE THREAD

**Issue by ioerjfoige0439i** [wpsharks/comet-cache#552]
Hi does s2member support Fastly as a CDN?

Here's some reference material:
https://github.com/fastly/WordPress-Plugin
https://wordpress.org/plugins/fastly/
https://crate.io/blog/fastly_traffic_spike/

**Comment by raamdev** [comment]
@ioerjfoige0439i Thanks for the question. Based on [the Fastly documentation](https://docs.fastly.com/guides/basic-setup/cname-instructions-for-most-providers), it appears that Fastly works the same way as CloudFlare, i.e., they ask you to point your entire domain at their servers so that _all_ requests go their servers before ever hitting your server.

That means it's not possible for the ZenCache Static CDN Filters (or _any_ WordPress caching plugin) to 'integrate' with Fastly. For more information on why this is, please see the following KB Article:
- [Why can’t I use Static CDN Filters with CloudFlare?](http://zencache.com/kb-article/why-cant-i-use-static-cdn-filters-with-cloudflare/)

**Comment by ioerjfoige0439i** [comment]
Interesting @raamdev! Let me ask you a question, would that be the same case for Akamai? I've decided to change CDN from MaxCDN/Amazon Cloudfront to either Akamai, Fastly or Highwinds because of this report: http://www.jwplayer.com/trends/ and even though they are a lot more expensive, the results say a lot! Thanks for the tip -- wonder if it's the same deal with Akamai??

**Comment by ioerjfoige0439i** [comment]
And if I did switch to Akamai, Fastly or Highwinds I can still basically just keep using ZenCache for page caching for each individual user on my s2Member site without interfering with these CDN's right?

**Comment by ioerjfoige0439i** [comment]
Also, see https://github.com/websharks/s2member/issues/689 I assume wordpress 4.3 doesn't affect zencache really right? I'm going to wait for an update to s2member though.

**Comment by raamdev** [comment]
> Let me ask you a question, would that be the same case for Akamai?

I'm not familiar with Akamai's specific services, but the information in the KB Article that I linked to applies to _any_ service where they ask you to change your DNS/CNAME configuration. If you are required to change your DNS/CNAME configuration for your domain, you are essentially redirecting all traffic to the CDN provider. 

> And if I did switch to Akamai, Fastly or Highwinds I can still basically just keep using ZenCache for page caching for each individual user on my s2Member site without interfering with these CDN's right?

That is correct. Even if you're using something like Fastly or CloudFlare, you should still be using a page caching plugin like ZenCache so that you improve the performance of WordPress itself. Those other services will have no effect on WordPress itself--for that, you need a caching plugin like ZenCache.

> I assume wordpress 4.3 doesn't affect zencache really right?

That is correct. I have not seen anything in WP 4.3 that will affect ZenCache and I have been testing ZenCache with WP v4.3-beta and now WP v4.3 since it was released.

**Comment by ioerjfoige0439i** [comment]
Awesome! Thanks for your help once again @raamdev I really appreciate these insightful answers!
