### ISSUE TITLE
Feature request: Auto-clear all posts when new post published/updated.

### ISSUE THREAD

**Issue by bridgeport** [wpsharks/comet-cache#553]
There's an existing option to 'Auto-Clear Designated "Posts Page"', but I think another to clear all "post" types would be useful. An example use case:

Let's say single blogs posts have a sidebar of most recent posts. If a new post is published or modified, it would shift the ordering of these sidebar items. But since ZenCache doesn't automatically purge other posts, their sidebar content would be stale. The entire cache would have to be purged, or deleted via FTP in order for these recent items to be updated.

The same would have to be if a post is modified. Timestamp changes could affect things as well as title changes.

Thanks.

**Comment by raamdev** [comment]
@bridgeport Thanks for the feature request and for the use-case scenario! That sounds like a good scenario to address.

@jaswsinc Any thoughts on how difficult this will be to implement? I'm thinking this might be tricky to implement correctly. We could look at the configured Permalink settings and then clear all cache files recursively that match that pattern, however that would also end up clearing all cached _Pages_.

Maybe a better solution to this issue would be to add support for User-Defined URIs to clear whenever a Post is cleared (see https://github.com/websharks/zencache/issues/111), and to support wildcards with that feature so that a site owner could, for example, specify `/blog/*` to clear all cache files for URIs under `/blog/` (i.e., all Posts) whenever any Post cache is cleared.

**Comment by jaswrks** [comment]
> Maybe a better solution to this issue would be to add support for User-Defined URIs to clear whenever a Post is cleared (see #111), and to support wildcards with that feature so that a site owner could, for example, specify /blog/\* to clear all cache files for URIs under /blog/ (i.e., all Posts) whenever any Post cache is cleared.

I agree, that would be a much better way to go about this, because without some form of configuration there is too much for work for ZenCache to do; i.e., to determine what exactly should be cleared. It's not impossible for ZenCache to do it, but I'd say it is not practical, given the overhead that would come with this; e.g., DB queries needed to determine and perhaps multiple directory scans.

On the other hand, if we have a user-supplied configuration that even supports wildcards, we can simply run that through a recursive regex directory scan and accomplish the task quickly in order to clear what any given site owner wants. That's more efficient, easier to implement, and also more flexible overall.

**Comment by raamdev** [comment]
@bridgeport I'm going to close this GitHub issue in favor of #111. I've gone ahead and [copied over some of your comments](https://github.com/websharks/zencache/issues/111#issuecomment-133766571) from this issue so that we can take your point into consideration when working on the feature described in #111.
