### ISSUE TITLE
v150919-RC: Cache Statistics placeholder when no stats available

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#565]
When installing ZenCache Pro on a site that does not have any prior Cache Stats history available, the Cache Stats page shows an empty area where the pie chart would normally be. It would be nice if this area was filled in with an example image of the pie chart, greyed out, with some text on it that says something like, "Cache Stats history not available, please check back later."

![2015-09-18_21-59-45](https://cloud.githubusercontent.com/assets/53005/9974117/97eb4c68-5e50-11e5-8d5c-e4ecc857d1df.png)

**Comment by jaswrks** [comment]
## Next Actions
- See [this line of JavaScript](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/js/menu-pages.js#L449) where the `$chartA` div is hidden when there are no stats.
- Same thing [here](https://github.com/websharks/zencache-pro/blob/000000-dev/src/client-s/js/menu-pages.js#L458) for Chart B (i.e., chart on the right side).
- Modify one or both of these, so that instead of hiding the chart, you fill it with an `<img />` tag.
  
  ``` js
  $chartA.html('<img src="..." />');
  // $chartA.hide();
  ```
- Compress `menu-pages.js` into `menu-pages.min.js`
- Submit PR.

**Comment by jaswrks** [comment]
See also: http://api.jquery.com/html/

**Comment by jaswrks** [comment]
## Generating the URL which leads to the image:
- After [this line of code](https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/closures/Plugin/MenuPageUtils.php#L41) add the following.
  
  ``` php
  'emptyStatsImageUrl' => $self->url('/src/client-s/images/empty-stats.png'),
  ```
- In JavaScript, you can access it like this:
  
  ``` js
  $chartA.html('<img src="' + plugin.escHtml(plugin.vars.emptyStatsImageUrl) + '" />');
  ```

**Comment by raamdev** [comment]
> Same thing here for Chart B (i.e., chart on the right side).

So there should be two empty-stats placeholder images?

**Comment by jaswrks** [comment]
Ideally, yes. However, you might decide that just doing `$chartA` is enough to convey what you need to.

**Comment by jaswrks** [comment]
> Compress menu-pages.js into menu-pages.min.js

Note that when you run the `compress-js` script I sent you, you can exclude the  `--old-style` arg, as ZenCache Pro is up-to-date and uses `.min.js` (new) instead of `-min.js` (old).

**Comment by raamdev** [comment]
![2015-09-23_21-47-26](https://cloud.githubusercontent.com/assets/53005/10063663/710c9006-623e-11e5-81d6-f4e76567736d.png)

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/issues/148
