### ISSUE TITLE
vaultpress flagging Core.php as web-based shell

### ISSUE THREAD

**Issue by erikanderson** [wpsharks/comet-cache#587]
<img width="785" alt="screen shot 2015-10-07 at 8 56 37 pm" src="https://cloud.githubusercontent.com/assets/4634290/10356583/ee9d3082-6d35-11e5-9f3a-d19586264d01.png">

I have contacted them to ask about this file and won't remove it in the mean time (since it would probably break caching)

**Comment by raamdev** [comment]
@erikanderson Thank you for the report. We have an existing GitHub issue open here to track this: https://github.com/websharks/zencache/issues/516

This is a false-positive being reported by VaultPress. We'll be working to find a way around this to prevent VaultPress from wrongly reporting `Core.php`, as that file is perfectly safe.

I'm going to close this GitHub issue in favor of https://github.com/websharks/zencache/issues/516. Please leave any additional details over there. :-)

**Comment by raamdev** [comment]
@erikanderson If you'd like to give our proposed workaround a try and see if that stops VaultPress from complaining, that would be super helpful. :-) See https://github.com/websharks/zencache/issues/516#issuecomment-127503919

Since we don't have access to VaultPress, the only way for us to test our fix is to have someone who is using VaultPress confirm the fix works.

**Comment by erikanderson** [comment]
Thanks, I will take a look at that issue and see if I can implement those fixes
