### ISSUE TITLE
clear cache animation causing problems - two issues

### ISSUE THREAD

**Issue by kNmnPyGGCwxk4zQoDD** [wpsharks/comet-cache#588]
hi, in previous versions of zencache I never had an issue until you added in this new animated clear cache thingy. It not only produces these weird lines (which stay on the screen) as it's trying to do it's animation but it also refuses to leave the screen. unlike the old pop up you had, I have to manually hit the x button for this one to close and if I don't -- then when I hit the clear cache button it animates in again but this time it DOES NOT actually even clear the cache. please add an option to revert to your old popup instead of this animation. I am using FF 41.0.1 if it makes any difference and haven't tested in other broswers.
![image](http://i.imgur.com/xghVsFx.png)

**Comment by jaswrks** [comment]
Thank you for the report. I just made an attempt to reproduce this in FF 40.0.3 and FF 41.0.1 bug without success; i.e., it seems to work as expected in Firefox also.

![2015-10-08_21-05-07](https://cloud.githubusercontent.com/assets/1563559/10386200/63b2bc50-6e00-11e5-880b-96a68416dc0a.png)

---

_**Tip:** Note that hovering over the popup will prevent it from being hidden automatically. This is intentional; i.e., so it won't disappear by itself if you mouse over it with the intention of reading the information contained in the popup and reviewing it more carefully._

**Comment by raamdev** [comment]
@kNmnPyGGCwxk4zQoDD Could you try reproducing this after you disable any Firefox Extensions that you have installed? It sounds like one of your extensions might be interfering with the JavaScript.

**Comment by raamdev** [comment]
Closing this as cannot reproduce. If you have any feedback on this issue, please update this GitHub issue and we can reopen it.
