### ISSUE TITLE
Aliased domain cache is not cleared

### ISSUE THREAD

**Issue by kristineds** [wpsharks/comet-cache#608]
Quick Cache Pro is not clearing cache for multiple sites/domains e.g. alias domains.  

Referencing Ticket: [Ticket # 9371](https://websharks.zendesk.com/agent/tickets/9371)

---

According to @jaswsinc:

> That is to be expected. ZenCache only clears the cache for the currently configured domain in a WordPress installation. The only way it can clear multiple sites is if you run it in a Multisite Network installation and click the "Wipe" button that is presented whenever you are running a Multisite Network
> 
> Having said that, whenever ZenCache automatically wipes the cache, everything is dealt with (for both domains), but unless you're running a Network, the Clear Cache button will not handle this gracefully I'm afraid.

**Comment by jaswrks** [comment]
@raamdev Thoughts on how to handle this? We could expose the **Wipe Cache** button for standard installs also I guess, but that seems like it would confuse most people; i.e., I imagine it is very rare for a standard installation to be associated with more than one domain.

However, there are cases when that could occur. In addition to the report above, there was this other case also. See: https://github.com/websharks/zencache/issues/101#issue-31823337

**Comment by raamdev** [comment]
@jaswsinc I would handle this by adding a new section under **ZenCache → Plugin Options → Automatic Cache Clearing → Misc. Auto-Clear Options** called "Auto-Clear These Aliased Domains Too?" that allows a site owner to define a comma-delimited list of aliased domains, so that ZenCache can take those additional domains into consideration whenever clearing the cache.

**Comment by yoffe** [comment]
Hi,
I think that this issue may occur also on a regular page update.
The cache engine need to update all the cached pages also in the alias domains...

**Comment by jaswrks** [comment]
@raamdev writes...

> define a comma-delimited list of aliased domains

Is there a specific reason why you feel this should be configurable?

Now that I'm looking at this again, it seems like the expected behavior would be for ZenCache to clear everything whenever it's running in a standard WP installation, right? So if that's the case, then maybe we just need to tell ZenCache that on a standard installation a cache clearing should clear all domain variations; i.e., behave as if there is not more than one domain to consider, but if there are, they are just cleared away at the same time. Nothing to configure that way.

**Comment by raamdev** [comment]
@jaswsinc If we visit aliased domain `alias.com`, generate a cache file that goes in `cache/alias-com/`, and then visit the primary site on `example.com` and update the post we visited via `alias.com`, then the automatic routines that clear the cache file for that post will only look in `cache/example-com/`, right? That seems like the problem with aliased domains.

An aliased domain is essentially another way of referencing the same site. So you could have a site `example.com` onto which you alias several other domains, e.g., `alias.com`, `foo.com`, etc. When someone visits `alias.com` or `foo.com`, they _do not_ get redirected to the main `example.com`, but instead they get to browse the entire site as whatever domain they typed in originally. That's how aliased domains are supposed to work.

So, to properly support aliased domains, ZenCache would need to know about all the domains it needs to consider when clearing cache files, e.g., a comma-delimited list supplied by the site owner.

If we're only talking about a full "Clear Cache" command, then yes, I agree, simply wiping out everything in `wp-content/cache/zencache/cache/*` would be sufficient. But that's not the problem with aliased domains I thought we were addressing. :-)

---

I haven't looked very carefully into how well supported aliased domains are with WordPress itself, so that might be something worth looking into. Also, seeing as how this is probably a not-so-common scenario, I'd be fine with making this something that you can support via an MU-Plugin (pass in an Array of domains). 

I'm assuming that such a change would just require adding a few lines of code to each of the clear cache routines, but if it would require more work than that I might just consider punting this or putting it on the back burner.

**Comment by jaswrks** [comment]
> If we visit aliased domain alias.com, generate a cache file that goes in cache/alias-com/, and then visit the primary site on example.com and update the post we visited via alias.com, then the automatic routines that clear the cache file for that post will only look in cache/example-com/, right? That seems like the problem with aliased domains.

Correct. That is the problem in my view also. The assumption (for the moment) is that a standard WP installation is only ever associated with one domain name. The `home_url()` domain.

> If we're only talking about a full "Clear Cache" command, then yes, I agree, simply wiping out everything in wp-content/cache/zencache/cache/\* would be sufficient. But that's not the problem with aliased domains I thought we were addressing. :-)

Copy that. I agree. I hadn't considered the _automatic_ clearing routines also.

> I haven't looked very carefully into how well supported aliased domains are with WordPress itself, so that might be something worth looking into. Also, seeing as how this is probably a not-so-common scenario, I'd be fine with making this something that you can support via an MU-Plugin (pass in an Array of domains).

I agree. I'm marking this as **Needs Research**.

**Comment by raamdev** [comment]
Referencing [this](https://github.com/websharks/comet-cache/issues/750) GitHub issue with the WPML plugin, which allows integration with aliased domains to support specific domains for versions of the site in different languages.

Quoting https://github.com/websharks/comet-cache/issues/750#issuecomment-215289030...

> We have two domain names, one for each language:
> 1. english-example.com
> 2. spanish-example.com
> 
> They are not sub-domains. The hyphens are deliberate.
> 
> The server is configured to use spanish-example.com as the root domain. english-example.com is an addon domain. Both domains point to the same server space.
> 
> WPML has an option for setting a domain name to use for the alternate language versions of the site.
> 
> When a request is made to the server, WPML detects which domain is requested. WordPress serves the requested page. WPML detects whether an alternate language version of the page exists and if one does then WPML displays a link to the alternate language version. The WordPress admin pages are served under the primary domain name.

Note that "addon domain" mentioned above is specifically referring to an aliased domain (`ServerAlias`), configured in Apache like the following (as described in [the WPML docs on this feature](https://wpml.org/faq/server-setting-for-languages-in-different-domains/):

```
<VirtualHost *>
  DocumentRoot /your_wp_install_directory/wordpress
  ServerName www.english-domain.com
  ServerAlias www.french-domain.fr

  ... your other stuff here ...
</VirtualHost>
```

---

My feeling is that Comet Cache _should_ support aliased domains. This doesn't seem very difficult to do: it seems it would just be a matter of allowing the site owner to define a list of aliased domains, and then Comet Cache could include those domains in the regex patterns when clearing cache files.

Thoughts @jaswsinc?

**Comment by jaswrks** [comment]
I agree that we should support aliased domains in CC. This is going to be something that needs to lay on top of (and/or together with) the existing functionality in CC that covers multisite domain mapping, because in the use case you mentioned with WPML we are talking about each individual site (whether it be in a network or not) being accessible over multiple domain variations.

So yeah, we would need to have a list of the aliased domains for multisite compat. Either by detecting popular plugin configurations and/or providing a box where the site owner can enter those.

On a single-site, I think this should be automatic; i.e. not need a list of aliases to work from. Any URL that is cleared on a standard WP installation should just be cleared by its URI and not by the full URL that includes a host name. That would resolve most of the issue here in that one change, because on a standard WP installation if we clear by URI alone, that would cover all domain variations.

Since our clearing routines operate on regex, it would be as simple as altering the regex; i.e., changing `/[host]/` to `/[^\/]+/` in order to clear all domain variations. In short, clearing by the URI alone.

**Comment by VR51** [comment]
A suggestion to speed this up a little bit. A temp. fix would be to add a 'Delete Cache Directory' button to the Comet Cache menu when aliased domains are in use. This way affected users won't need to manually delete the cache directory via FTP.

**Comment by raamdev** [comment]
@jaswsinc So I see this as involving two fixes: one for Standard WP installations and one for Multisite WP installations, correct? 

If that's the case, let's start with improving this for Standard WP installations. If all that's required is an update to the RegEx, that sounds easy enough. 

I think it's a great idea to clear all variations of the domain when operating on a standard WP installation, as that seems to be what would be expected anyway, e.g., if the site has both `http` and `https` variations of their URL and their site is mixing the two, it would be nice to ensure that both variations of the cache are cleared when necessary.

For Multisite installations, I can see how it will get a little complicated. If each site in a multisite network can have its own domain _and_ its own set of aliased domains, then we'd need a way for the Network Admin to provide a list that maps Sites to Aliased Domains (e.g., `site1.com:alias1.com,alias2.com`). 

From what I've seen, all of the reports that mention this aliased domain issue have been Standard WP sites not Multisite installations, so I think we should start by getting this fixed for Standard WP sites and if there's a demand for this 'feature' in Multisite as well, we can come back and add that later.

**Comment by jaswrks** [comment]
@raamdev Sounds like a plan ...

## General Outline for Standard Installations
- After [this line](https://github.com/websharks/comet-cache-pro/blob/000000-dev/src/includes/traits/Shared/CacheDirUtils.php#L271) add the following:
  
  ``` php
  // On a standard installation delete from all hosts.
  // See: <https://github.com/websharks/comet-cache/issues/608>
  
  if (!is_multisite() && !$___considering_domain_mapping) {
      $regex = ltrim($regex, '^\\/');
  
      if (mb_strpos($regex, '(?:\/') === 0 || mb_strpos($regex, '(\/') === 0) {
          $regex = '/^https?\/[^\/]+'.$regex;
      } else {
          $regex = '/^https?\/[^\/]+\/'.$regex;
      }
      return $this->deleteFilesFromCacheDir($regex, $check_max_age);
  }
  
  ```

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix**: If your site uses aliased domains, Comet Cache now properly considers all possible domain variations when it clears the cache on WP Standard installations. Props @kristineds, @jaswsinc, @yoffe, and @VR51. See [Issue #608](https://github.com/websharks/comet-cache/issues/608).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#608).
