### ISSUE TITLE
Warning about lack of xml sitemap when the sitemap exists

### ISSUE THREAD

**Issue by KTS915** [wpsharks/comet-cache#615]
This relates to the new feature released and documented at Issue #555.

I tried the RC with this feature, using the Simple WP Sitemap plugin, and had no problems. I had the same flawless experience when I then installed the public version -- except on one site, where it claimed that there was no sitemap.xml, even though the sitemap plugin was already activated and my browser could locate the sitemap.

I thought that maybe that was just user error on my part -- after all, the other installs had worked fine -- but there is now also this report on the Zen Cache wordpress.org forum: https://wordpress.org/support/topic/sitemap-problem-15?replies=1 

That user is using a different sitemap plugin from me, so it doesn't seem that that could be the cause.

This leads to two questions:
1. Is Zen Cache now generating warnings when everything is in fact OK?
2. Is there a way to tell whether (whatever the warning says) Zen Cache is making use of the sitemap.xml file?

**Comment by jaswrks** [comment]
@KTS915 Thanks for the report! :-)

_Referencing: https://github.com/websharks/zencache-pro/blob/151105/src/includes/classes/AutoCache.php#L246-L258_

This warning occurs whenever:
- You have the ZenCache Auto-Cache Engine enabled, and:
  - The `/sitemap.xml` file leads to any HTTP status code that is >= 400; e.g., a 404 error.
  - The `/sitemap.xml` file is loaded without an XML `Content-Type` header, which would be expected.
  - The `/sitemap.xml` is completely unreachable; e.g., an HTTP connection failure.

A quick review of the code that issues this warning doesn't show any problems so far as I can see, but I will keep my eyes open for more reports like this one. Please let us know if you encounter any others.

> 1. Is there a way to tell whether (whatever the warning says) Zen Cache is making use of the sitemap.xml file?

If the warning goes away, or if you inspect the `/wp-content/cache/zencache/cache/zc-auto-cache.log` file and find that URLs from your `/sitemap.xml` file are in fact being cached, according to the log entries.

**Comment by raamdev** [comment]
> except on one site, where it claimed that there was no sitemap.xml, even though the sitemap plugin was already activated and my browser could locate the sitemap.

@KTS915 Would it be possible to get the output of `phpinfo()` on that site so that we can review the PHP configuration? It sounds to me like there _might_ be an issue with that server connecting to its own URL.

**Comment by KTS915** [comment]
@raamdev,

I've installed the WordPress phpinfor{} plugin. There's an awful lot of info here! Which bit do you need? Just the PHP Variables?

**Comment by raamdev** [comment]
@KTS915 If you can copy/paste all of it into an "unlisted" http://pastebin.com and then paste the link on Slack (so it stays private), I should be able to find the bit(s) that I need.

**Comment by raamdev** [comment]
@KTS915 I just discovered an issue with the error reporting in that notice; see https://github.com/websharks/zencache/issues/616. The problem is that once you dismiss the notice, _it will never reappear_, even if the problem still exists. This was an oversight in the creation of that notice, so I opened https://github.com/websharks/zencache/issues/616 to resolve that in the next update.

For now, there really isn't any easy way of determining if ZenCache reports that your XML Sitemap is _still_ unreachable, at least not without deleting the value of `zencache_notices` in your `wp_options` database table.

If you are able to reach your XML Sitemap in the browser and the `wp-content/cache/zencache/zencache-auto-cache.log` file shows that pages on your site are being visited by the Auto-Cache Engine, then there's likely nothing wrong and the initial notice that you dismissed was probably an anomaly.

In any case, we'll have this improved in the next ZenCache Pro release. :-)

I'm going to close this issue for now, but if you have any new information to report, please let me know and I'll reopen this.

**Comment by rballengee** [comment]
Hi, I stumbled on this thread this evening, frustrated and looking for answers. About a week ago, I first installed ZenCache, hoping it might provide a caching solution that wouldn't upend a WPMU membership plugin. It did, with some thinking, but it unfortunately has killed my sitemaps' compatibility with Google Webmasters Tools. 

Although I didn't make a change in my sitemap plugin (XML Sitemap &  Google News feeds), I now have a warning in GWT for my sitemaps it generates, saying, "Your Sitemap does not appear to be in a supported format." However, it validates using myriad tools, and a sitemap generated from xml-sitemaps.com passes muster. I tried a bunch of different sitemap plugins to see if a change might work, but it all boils down to ZenCache. I'm not sure what to do, but I don't want to have to go to the same site every time I post or do it manually. 

I guess the nuclear option is to create a new database, only move over the crucial stuff and start over, but, again, I don't want to do that.

The help is much appreciated.

**Comment by KTS915** [comment]
@rballengee,

Are you caching logged-in members?

**Comment by rballengee** [comment]
I'm not

**Comment by KTS915** [comment]
Hmm, OK. I am still wondering whether having protected pages is somehow relevant (perhaps because Google can't access all the pages in the sitemap).

**Comment by rballengee** [comment]
I'm starting to suspect the same. Went into GWT since, as you'd expect, I
have a hike in Soft 404s, and had Google fetch some of the URLs, including
the sitemap.

All return: Fatal error&lt;/b&gt;: Call to a member function
add_membership() on a non-object in
&lt;b&gt;/home/thegol5/public_html/wp-content/plugins/membership/app/addon/searchindex/class-ms-addon-searchindex.php&lt;/b&gt;
on line &lt;b&gt;286

However, when I ask Google to render the page as a normal person would see
it, then it shows it. So the thread here may have sent me in a wrong
direction.

**Comment by theperfectwill** [comment]
@jaswsinc @raamdev 

I am building a new version of a client's site, but you can take a look at the live version that still has this issue, that would help? 

The issue started after the latest Zencache or Yoast update. I'm not sure which.

I can still access and verify the xml sitemap is at it's location, but I still get the warning that Zencache couldn't find that file. 

This is using the Pro version.

**Comment by raamdev** [comment]
@NoahjChampion If you look at the `wp-content/cache/zencache/zencache-auto-cache.log` file, does it look like the Auto-Cache Engine is working, i.e., like it's pre-caching the pages?

**Comment by theperfectwill** [comment]
@raamdev 

Sort of...

**Looking at the .log:**
- It looks like there are only issues with Woocommerce pages. 
- These pages are /my account, /checkout, /cart, /product/*... in which they return the following: 
  `"Error: Too many redirects."` 
- However, the pages (my account, checkout, cart) are set in my URI Exclusions. So should there even be an attempt to cache these pages? 

**For the "/product/\* page:** 
- It is ONLY ONE product that is giving the `"Error: Too many redirects."` and that would be because of this plugin I'm fairly confident... 
  @ http://codecanyon.net/item/woo-detail-product-page-builder/7605299
- Screenshot of it's redirect option 
  @ http://take.ms/eaZHy
- Though, I've gotten rid of this plugin on a new build, this plugin is only set up on one product page and it has a redirect to a normal Wordpress page and pulls the Woo product data into that page so a normal "page template" can be used for the product display instead of Woocommerce's default product template. 

**Lastly:** 
- I played around with clearing the cache and monitoring it. I can see the auto caching is working for posts and custom post types, but NOT pages, not even the index.html (home page) is created. I can verify that physically as well because when I visit the home or any "page" the caching won't cache upon my visit. Again, that is just for pages. 
- Other than that I can see the auto cache is working because it cached all the blog posts and returned the following: 
  `Run Completed: Thu, 03 Dec 15 01:25:46 +0000`
  `Total URLs: 388`
  `Total Time: 420.84843 seconds`

**Comment by jaswrks** [comment]
Just noting this related issue: https://github.com/websharks/zencache/issues/618

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#615).
