### ISSUE TITLE
Error message with .htaccess [ZenCache Pro 151114]

### ISSUE THREAD

**Issue by Kalfer** [wpsharks/comet-cache#617]
When I make any changes to the settings, and pulse on "**Save All Changes**", I get the following error message:

_"Failed to update your /.htaccess file automatically. Most likely a permissions error. Please make sure it has permissions 644 or higher (perhaps 666). Once you've done this, please try saving the ZenCache options again."_

This did not happen in previous versions of ZenCache Pro.
The message remains, even changing the permissions to 666.

Thanks

**Comment by raamdev** [comment]
@Kalfer The latest release adds a new feature that writes necessary code to the `.htaccess` file and that feature did not exist in previous releases, hence the reason you're only now seeing that error message.

A few questions:
- Are your **WordPress Address (URL)** and **Site Address (URL)** (in **Dashboard → Settings -- General**) different or the same?
- Is your `.htaccess` located inside the WordPress directory (where `wp-config.php`, etc., are located) or is it outside that directory (e.g., at the root path)?
- Which version of PHP are you running?

**Comment by Kalfer** [comment]
Answers to your questions:

1- They have the same URL.
2- Both are on the same path. (/public_html)
3- My server uses PHP 5.4.32

Thanks

**Comment by jaswrks** [comment]
@Kalfer Do you have `DISALLOW_FILE_MODS` defined in your `/wp-config.php` file?
- e.g., `define('DISALLOW_FILE_MODS', true);`

---

If so, try removing that or setting it to false and try again.
- i.e., `define('DISALLOW_FILE_MODS', false');`

**Comment by Kalfer** [comment]
Not, my wp-config.php does not have that line of code.

Thanks

**Comment by jaswrks** [comment]
@Kalfer Thank you. Interesting. I'm not seeing any reason for you to get that error then.

Would you mind running a test for me?

## Debugging Steps
- Enable ZenCache, if you haven't already.
- Using FTP, create this file in the root of your WordPress installation, in the same directory as `wp-config.php`. Name the file: `zencache-test.php`
  
  ``` php
  <?php
  require_once dirname(__FILE__).'/wp-load.php';
  header('Content-Type: text/plain; charset=utf-8');
  
  global $zencache;
  echo $zencache->wpHomePath()."\n";
  echo $zencache->findHtaccessFile()."\n";
  var_dump(is_readable($zencache->findHtaccessFile()));
  var_dump(is_writable($zencache->findHtaccessFile()));
  print_r(stat($zencache->findHtaccessFile()));
  ```
- Open `http://yoursite.com/zencache-test.php` in a browser and paste the output for us please.
- Delete the `/zencache-test.php` file.

---

Example output: http://jason.websharks-inc.net/zencache-test.php

**Comment by Kalfer** [comment]
Hi,
I send the test result:

/home/cubierta/public_html/
/home/cubierta/public_html/.htaccess
bool(true)
bool(true)
Array
(
    [0] => 118
    [1] => 26345482
    [2] => 33188
    [3] => 1
    [4] => 502
    [5] => 513
    [6] => 0
    [7] => 1268
    [8] => 1447954233
    [9] => 1442395252
    [10] => 1447867586
    [11] => 4096
    [12] => 8
    [dev] => 118
    [ino] => 26345482
    [mode] => 33188
    [nlink] => 1
    [uid] => 502
    [gid] => 513
    [rdev] => 0
    [size] => 1268
    [atime] => 1447954233
    [mtime] => 1442395252
    [ctime] => 1447867586
    [blksize] => 4096
    [blocks] => 8
)

**Comment by jaswrks** [comment]
@Kalfer Thank you. That narrows it down quite a bit. What I am left with in terms of debugging, is [this line of code](https://github.com/websharks/zencache-pro/blob/151105/src/includes/closures/Plugin/HtaccessUtils.php#L96). In short, if your existing `.htaccess` file already has something in it related to ZenCache, it might be causing you this problem.

Can you paste the contents of your `.htaccess` file please?

Or, if you don't want to do that, please review it yourself. Let me know if you currently have anything in there that is related to ZenCache, or labeled with the word `ZenCache` anywhere (even if it's just a code comment). If so, please paste in that snippet for us to look at.

**Comment by jaswrks** [comment]
@raamdev One possible cause, is [this line of code](https://github.com/websharks/zencache-pro/blob/151105/src/includes/closures/Plugin/HtaccessUtils.php#L96). Notice that just above this line, we are stripping the `.htaccess` tweaks that were inserted by ZenCache, and then checking to confirm that they were in fact removed. However, that check is simply scanning for any remaining instances of the word "ZenCache" (i.e., `NAME`). If the site owner has used any code samples we provide in our KB (or via the Dashboard; e.g., to enable GZIP Compression), and they happen to comment on that block and add a label of `ZenCache` somewhere (caSe insensitive), this could cause some trouble. So the removal routine thinks it failed, when actually it didn't. That's something we can improve.

**Comment by Kalfer** [comment]
Here my .htaccess : 

# -FrontPage-

IndexIgnore .htaccess _/.??_ _~ *# */HEADER_ _/README_ _/_vti_
<Limit GET POST>
order deny,allow
deny from all
allow from all
</Limit>
<Limit PUT DELETE>
order deny,allow
deny from all
</Limit>
AuthName XXXXXXX.com
AuthUserFile /home/XXXX/public_html/_vti_pvt/service.pwd
AuthGroupFile /home/XXXX/public_html/_vti_pvt/service.grp

# BEGIN WordPress

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

# Para Zencache

<IfModule deflate_module>
    <IfModule filter_module>
        AddOutputFilterByType DEFLATE text/plain text/html
        AddOutputFilterByType DEFLATE text/xml application/xml application/xhtml+xml application/xml-dtd
        AddOutputFilterByType DEFLATE application/rdf+xml application/rss+xml application/atom+xml image/svg+xml
        AddOutputFilterByType DEFLATE text/css text/javascript application/javascript application/x-javascript
        AddOutputFilterByType DEFLATE font/otf font/opentype application/font-otf application/x-font-otf
        AddOutputFilterByType DEFLATE font/ttf font/truetype application/font-ttf application/x-font-ttf
    </IfModule>
</IfModule>

# END Zencache

**Comment by raamdev** [comment]
@Kalfer Thank you very much! I have confirmed this is a bug caused by the presence of an existing occurrence of the word `zencache` inside your `.htaccess` file. 

If you simply rename `# Para Zencache` and `# END Zencache` to `# Para ZC` and `# END ZC` and then click "Save All Changes" inside the ZenCache Options panel (no need to change any settings; just click the "Save All Changes" button), the error you're seeing on the Dashboard should go away. 

We'll get this fixed in the next release. :-)

**Comment by raamdev** [comment]
@jaswsinc writes...

> So the removal routine thinks it failed, when actually it didn't. That's something we can improve.

Yup, that's exactly what's happening. I just confirmed this using the snippet of code from @Kalfer's `.htaccess` on my test site--I got the same Dashboard error that he reported.

So do you think we should just remove [that check](https://github.com/websharks/zencache-pro/blob/151105/src/includes/closures/Plugin/HtaccessUtils.php#L96) altogether? I reviewed the codebase and I'm not seeing any places where it's _really_ necessary that we have that check there. It seems safe to assume that if we can successfully read and write to the `.htaccess` file, and run the regex that strips out `# BEGIN ZenCache` and `# END ZenCache`, that we can be fairly certain _our_ copy is gone.

If we decide to keep such a check in there, we'd still need to consider that a site owner might edit their `.htaccess` file and rename our `# BEGIN` and `# END` comments anyway.

And if instead of checking for just `NAME` we check for `'# BEGIN '.NAME` and `'# END '.NAME`, that doesn't solve the problem because a site owner may have already added a `# BEGIN ZenCache` and `# END ZenCache` comment to their `.htaccess` file, similar to how @Kalfer did.

---

### There's an even bigger issue here:

If a site owner _is already using_ `# BEGIN ZenCache` and `# END ZenCache` comments in their `.htaccess` file for some custom rules they added for ZenCache, **the latest version of ZenCache will delete their custom rules** and replace them with whatever ZenCache adds.

Yikes.

So, I think the best solution to this whole problem is to use a somewhat unique key of some sort in our start and end markers, something like this so that we can look for something specific: 

``` htaccess
# BEGIN ZenCache (Please do not remove this comment key: 2hetel1r&TekIF0)
[...]
# END ZenCache (Please do not remove this comment key: 2hetel1r&TekIF0)
```

**Comment by jaswrks** [comment]
> So, I think the best solution to this whole problem is to use a somewhat unique key

I love this idea. That would be perfect.

**Comment by raamdev** [comment]
@Kalfer I'm going to close this issue in favor of the bug report that I opened here: https://github.com/websharks/zencache/issues/620 Fixing that bug will solve the problem you described here (which I re-described in this comment: https://github.com/websharks/zencache/issues/620#issuecomment-158693865). Thanks so much for helping us debug this! We'll get this fixed in the next release. If you'd like to follow updates on https://github.com/websharks/zencache/issues/620, please subscribe to that GitHub issue.

**Comment by Kalfer** [comment]
Hi @Raam Dev, 

I've made these changes, and now the error does not appear.
Thank you.

**Comment by jaswrks** [comment]
@Kalfer Great! Thanks for the feedback on this.
