### ISSUE TITLE
ZenCache Lite 151107, Editors Saving a Draft sees Notices

### ISSUE THREAD

**Issue by eurobank** [wpsharks/comet-cache#625]
My Editor (editors WP class) sometimes he sees notices from ZenCache about refreshing the Home Page when SAVING a DRAFT blog post.

"ZenCache: detected changes. Found 1 file in the cache for the designated "Home Page"; auto-clearing."

Two problems: the Editors shouldn't see anything IMHO, and ANYONE saving a draft should not clear the Home Page or whatever.

Thanks !

**Comment by jaswrks** [comment]
> the Editors shouldn't see anything IMHO

Thanks for that feedback.
- As it exists now, anyone who can `activate_plugins` can see those notices.
- You can also hide these notices entirely in ZenCache Pro.

> saving a draft should not clear the Home Page or whatever.

Agree. This has been fixed in the pro version, and we will push those changes to the lite version soon.

To confirm, I ran tests against both lite and pro just now.
- Saving a draft in pro version, no problem.
- Saving a draft in lite version, clears the home page.

**Comment by raamdev** [comment]
@eurobank I've created a feature request for the ability to define the Roles/Capabilities allowed to see the Dashboard notices: https://github.com/websharks/zencache/issues/627#issue-119313034

The fix for the bug with saving a Post as Draft clearing the Home Page will go out with the next release (within the next 2 weeks). Thanks for your patience! :-)

**Comment by raamdev** [comment]
Next Lite Release Changelog:
- **Bug Fix**: Fixed a bug where saving a Post/Page as a Draft as a user with an Editor role would unnecessarily clear the Home Page cache. See [Issue #625](https://github.com/websharks/zencache/issues/625).

**Comment by raamdev** [comment]
**ZenCache v160222** has been released and includes changes from this GitHub Issue. See the [v160222 announcement](http://zencache.com/zencache-v160222-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#625).
