### ISSUE TITLE
Bug: Using `define('ZENCACHE_ALLOWED', FALSE);` to Disable Zencache, Should Disable the ZenCache Static CDN Filters

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#628]
## Overview

Customer tried using `define('ZENCACHE_ALLOWED', FALSE); to disable CDN support for specific pages, but was not working properly.
## Steps to Reproduce
- Set `define('ZENCACHE_ALLOWED', FALSE);` or `define('DONOTCACHEPAGE', TRUE);`
- Check if Static CDN Filters/ZenCache itself are disabled
## Expected Behavior

Setting `define('ZENCACHE_ALLOWED', FALSE);` or `define('DONOTCACHEPAGE', TRUE);` should disable the ZenCache Static CDN Filters as well as the caching itself. There should probably be a separate constant to allow for specifically disabling Static CDN Filters and the HTML Compressor (e.g., `ZENCACHE_CDN_ALLOWED` and `ZENCACHE_HTMLC_ALLOWED`). 
## Observed Behavior

Customer reported that they tried to disable CDN support for specific pages. They were using `define('ZENCACHE_ALLOWED', FALSE);` to disable Zencache, but reported that it still uses static CDN if globally enabled.

_

referenced in internal ticket:  https://websharks.zendesk.com/agent/tickets/9784

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Enhancement**: The Static CDN Filters now attempt to obey the `ZENCACHE_ALLOWED` and `DONOTCACHEPAGE` constants so that Static CDN Filters are not applied when caching is disabled. However, due to the way Static CDN Filters are implemented this is not always reliable. If you need to programmatically disable Static CDN Filters, see [this article](http://zencache.com/kb-article/how-do-i-disable-static-cdn-filters-via-php/). See [Issue #628](https://github.com/websharks/zencache/issues/628).

**Comment by raamdev** [comment]
**ZenCache v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#628).
