### ISSUE TITLE
Bug: Overcautious failure to cache when nonce in markup

### ISSUE THREAD

**Issue by KTS915** [wpsharks/comet-cache#645]
This is related to #642, but Akismet is not involved. 

ZenCache Pro v151220 apparently now refuses to cache any page (at least for logged-in users) where some mention is made of `nonce`. This is pretty serious because it means effectively that I can't cache any pages on some of my sites.

Plugins that include `nonce` in the markup include those, like BAW Login/Logout menu, that provide a means of logging in and out, and plugins that handle comments. Obviously, this is a pretty wide-ranging issue. 

I can also see that ZenCache Pro v151220 itself adds `nonce` to the markup, though I don't know whether this is contributing to the problem.

I have reverted to v151105 for the moment, and have no problems. I notice that v151105 does not appear to add `nonce` to the markup.

**Comment by raamdev** [comment]
@KTS915 Thanks for the report.

ZenCache should be automatically disabling the Akismet nonce (which is supported by Akismet for scenarios such as when caching pages), however a bug in the way Akismet reads the value of the filtered option is preventing ZenCache v15120 from working as expected (see https://github.com/websharks/zencache/issues/642; we have a temporary workaround posted in that issue too if you're using Akismet).

We also have a feature request open to make it possible to disable the nonce exclusion; see https://github.com/websharks/zencache/issues/637. It sounds like that's what you need--a way of telling ZenCache to ignore nonce values in the HTML and cache the page anyway.

ZenCache never adds a nonce to any front-end pages; it only uses them on the Dashboard when generating links for the options pages. Since ZenCache only caches the front-end of the site, the nonce values that ZenCache adds have no effect.

Caching nonce values is a bad idea, since the nonce is time-sensitive. That's why we made the decision to have ZenCache ignore HTML that contains any nonce values. Please see the original issue, https://github.com/websharks/zencache/issues/601, for full details.

---

I'm going to close this issue in favor of https://github.com/websharks/zencache/issues/637, which shold resolve this issue for you.

**Comment by KTS915** [comment]
OK, thanks, Raam. I don't use Akismet on any sites. I look forward to finding out how to disable the nonce exclusion.

**Comment by raamdev** [comment]
**ZenCache Pro v160103** has been released and includes changes from this GitHub Issue. See the [v160103 announcement](http://zencache.com/zencache-pro-v160103-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference #637.
