### ISSUE TITLE
html Compression is not working on https

### ISSUE THREAD

**Issue by Metacowboy** [wpsharks/comet-cache#656]
the Plugin compress the files perfect on a http request for the https no compression is done

**Comment by raamdev** [comment]
@Metacowboy Have you tested this in a [Clean WordPress Installation](http://zencache.com/kb-article/testing-zencache-in-a-clean-wordpress-installation/)? HTML Compression for HTTPS requests works fine for me.

**Comment by GermontZ** [comment]
@Metacowboy  Do you use Cloudflare?

**Comment by MarioKnight** [comment]
This might be related (if not please split this off into a separate issue) as at times, I have seen my https site appear busted to an extent.  It seemed to be random, and clearing the cache always seemed to fix it.  Following the automatic WP core security update, it was noticed that the issue was coming up.  I finally had the ability to attempt to look into it, and it seems that one of the compressed files was being served via http:

`<link type="text/css" rel="stylesheet" href="http://missdream.org/wp-content/cache/zencache/htmlc/public/missdream-org/6/4/d/1/8/f22300ed92bb28cbbb0c775076a6d524-compressor-part.css" media="all"/>`

When I noticed this, I cleared the cache, and upon refresh directly after, this was changed to reflect the correct https and everything looked correct again:

`<link type="text/css" rel="stylesheet" href="https://missdream.org/wp-content/cache/zencache/htmlc/public/missdream-org/6/4/d/1/8/929f3fc2acb978df2bef9e23601d9dc8-compressor-part.css" media="all"/>`

What stood out as odd to me was that this text/css link was the only ZenCache Pro / HTML Compressor generated reference that was switched to http, all others showed the correct https, and the WP generated references/images/etc were either protocol-less (CloudFlare) or the full URL.

I have only seen this behavior after automatic core updates, and it seems it is safe to say that it is only the same link that is affected as the page is broken in the same way each time.

@Metacowboy , if you clear the cache on your site, does the https site load as it should?  If so, our issues might be related and I hope my additional information can assist.  If not, I'll break my issue in a different ticket.

**Comment by raamdev** [comment]
@MarioKnight Thanks so much for the detailed report. :-)

> this text/css link was the only ZenCache Pro / HTML Compressor generated reference that was switched to http, all others showed the correct https
> [...]
> I have only seen this behavior after automatic core updates

@jaswsinc My instinct tells me that this sounds like there might be a bug in ZenCache that lets this happen when automatic updates occur. Any thoughts?

**Comment by jaswrks** [comment]
A related bug was found and fixed not too long ago in the HTML Compressor, documented here: https://github.com/websharks/html-compressor/releases/tag/150923

@Metacowboy @MarioKnight Do we know which version of the HTML Compressor (or of ZenCache) was in use when this occurred?

**Comment by MarioKnight** [comment]
I can't speak of previous times when I was unable to properly record any information, but last week ZCP 160103 was in place when the automatic WP core update of 4.4.1 to 4.4.2 took place and the behavior described above happened.
