### ISSUE TITLE
Evaluate Custom PHP Code does not evaluate custom PHP code

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#664]
## Steps to reproduce
1. Install ZenCache Pro v160127, activate, enable, and add the following to **ZenCache → Plugin Options → Manual Cache Clearing → Evaluate Custom PHP Code when Clearing the Cache?**
   
   ``` php
   <?php file_put_contents(WP_CONTENT_DIR.'/zc-log-test.log', "SUCCESS!"."\n\n----------------------------\n\n", FILE_APPEND); ?>
   ```
2. Visit the site to cache some pages
3. Clear the cache manually using the Clear Cache button in the admin bar
## Expected behavior

The custom PHP code should be run, generating `WP_CONTENT_DIR.'/zc-log-test.log'`.
## Observed behavior

Log file does not exist and PHP code does not appear to run. No PHP errors are thrown in the main debug file.

**Comment by jaswrks** [comment]
Does it make any difference if you remove the PHP tags?

**Comment by raamdev** [comment]
> Does it make any difference if you remove the PHP tags?

No, no difference.

**Comment by raamdev** [comment]
@jaswsinc Any idea what the problem might be here? I looked into this a bit and nothing jumped out at me. 

I'm trying to see if we can get this fixed before the next ZenCache RC (targeted for Monday night, February 15th).

**Comment by jaswrks** [comment]
It looks like the problem is with [this line of code](https://github.com/websharks/zencache-pro/blob/160211/src/includes/closures/Plugin/WcpEvalUtils.php#L24). This check returns false for language constructs like `eval()` because they are not actually functions as far as `function_exists()` and `is_callable()` are concerned.

I worked around this in Comment Mail by whitelisting a set of language constructs that will bypass the `function_exists()` and `is_callable()` checks. See [this file](https://github.com/websharks/comment-mail-pro/blob/160213/comment-mail-pro/includes/classes/utils-php.php#L31-L47) for an example.

It's important that we _do_ run a check like this for eval, because `eval()` is one that is in fact blacklisted by Suhosin or added to the list of disabled functions. However, as far as `function_exists()` and `is_callable()` are concerned, we cannot make that particular check, so we need to bypass those calls whenever the function being tested is actually a language construct.

**Comment by raamdev** [comment]
> It looks like the problem is with this line of code.

@jaswsinc Awesome! Thanks for finding that. :-) I fixed and tested via https://github.com/websharks/zencache-pro/issues/215.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **Bug Fix**: Fixed a bug that was preventing the "Evaluate Custom PHP Code when Clearing the Cache" feature from working properly. This bug resulted in the custom code not being run when the cache was cleared manually. See [Issue #664](https://github.com/websharks/zencache/issues/664).

**Comment by raamdev** [comment]
**ZenCache v160222** has been released and includes changes from this GitHub Issue. See the [v160222 announcement](http://zencache.com/zencache-v160222-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#664).
