### ISSUE TITLE
Comet Cache Pro not caching logged-in users with s2Member

### ISSUE THREAD

**Issue by KTS915** [wpsharks/comet-cache#676]
I have just moved a test site from ZC Pro to CC Pro, and I see that, although I have CC Pro set to cache logged-in members, it is refusing to do so because s2Member is setting the PHP constant DONOTCACHEPAGE.

Obviously, s2Member is right to do that, but ZC Pro enabled that to be overridden if it was set to cache logged-in users. Can that be added back in to CC Pro, please?

**Comment by raamdev** [comment]
> Obviously, s2Member is right to do that, but ZC Pro enabled that to be overridden if it was set to cache logged-in users. Can that be added back in to CC Pro, please?

Hmm, I don't recall ZenCache doing any overriding of that for s2Member, but I'll need to take a closer look at this and see if I can reproduce this. The Comet Cache Pro codebase is the ZenCache Pro codebase; we didn't remove any feature code. Do you recall which version of ZenCache Pro you were using that was overriding s2Member's `DONOTCACHEPAGE`?

@jaswsinc Any thoughts here?

**Comment by KTS915** [comment]
Version 160103 of ZC Pro certainly permits caching forlogged-in members while s2Member is running, and so have previous versions of ZCP/Quick Cache Pro for at least a year, I think (from which I infer ZCP was overriding the DONOTCACHEPAGE constant.

I am going to update ZCP on another test site to v160222 and see if it still works with that.

**Comment by KTS915** [comment]
Interesting! v160222 of ZCP does not permit caching of logged-in users with s2Member running.

So the code change is between versions 160103 and 160222 of ZCP.

**Comment by KTS915** [comment]
Just another post to note this KB post: https://s2member.com/kb-article/is-s2member-compatible-with-caching-plugins/

It states: "Tip: ZenCache has a unique ability to cache logged-in users too, which is highly effective whenever it runs alongside the s2Member Pro application; keeping WordPress fast even when a user is logged in as a member. Very impressive!"

**Comment by KTS915** [comment]
Sorry, I was wrong about ZC Pro v160222: it does permit caching of logged-in users while s2member is running. (Another plugin on that site was preventing caching there.) So it seems that there is a difference between ZC Pro v160222 and CC Pro v160223.

I am going to try changing from ZC Pro to CC Pro on this site to see if the same problem occurs or not.

**Comment by KTS915** [comment]
OK, I have now changed this site to CC Pro too: this time, version 160223.1. And it will not cache logged-in users while s2member is running.

So there is definitely a difference somewhere between ZC Pro v160222 and CC Pro v160223.

**Comment by jaswrks** [comment]
Agree. We have some additional code in the s2Member plugin itself that accomplishes full compatibility between the two, and so we will need to update the s2Member codebase so that it looks for Comet Cache PHP Constants; i.e., the name change may require changes in s2Member also. Thanks for reporting! I'm going to address this before a release of s2 this week.

**Comment by raamdev** [comment]
@KTS915 Thanks for the detailed testing reports. As @jaswsinc pointed out, this is because s2Member is not integrating properly with Comet Cache, not that Comet Cache is not integrating properly with s2Member.

I've opened an s2Member issue to track this here: https://github.com/websharks/s2member/issues/888

Since this isn't a Comet Cache issue, I'm going to close this in favor of the s2Member issue.

**Comment by KTS915** [comment]
@jaswsinc, @raamdev: Thanks for the explanations!
