### ISSUE TITLE
Comet Cache "Auto Cache Engine" not saving pages.

### ISSUE THREAD

**Issue by digitalhexcode** [wpsharks/comet-cache#679]
I noticed after updating from Zencache Pro to Comet Cache that the Auto Cache Engine runs, however, it doesn't actually save any of the files. I can see in the cc-auto-cache.log that it runs every 15 minutes without errors loading many pages but none of the files are being saved in the /cache/comet-cache/cache/http/ directory. If I manually goto a web page it will cache it and save it properly. Wondering if anyone else is having this issue?  Thanks

**Comment by raamdev** [comment]
@digitalhexcode Thanks so much for the report. It looks like this is a bug. 

The issue is that we are mixing two different constants in the Auto-Cache Engine code (`SLUG_TD` and `GLOBAL_NS`) when we should be using just one or the other. The reason this wasn't an issue in ZenCache is that those two constants happened to have been set to the same thing (`zencache`). 

When we rebranded the code for Comet Cache (which has a space in the name), `SLUG_TD` was set to `comet-cache` while `GLOBAL_NS` was set to `comet_cache` (hyphen vs underscore). That difference caused the Auto-Cache Engine to no longer work as expected, as it was setting `SLUG_TD` in one place but then looking for `GLOBAL_NS` to make sure it should run in another place.

We'll have this fixed for the next release.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Bug Fix** (Pro): Fixed an Auto-Cache Engine bug that was preventing the Auto-Cache Engine from generating cached pages. Props @digitalhexcode for reporting. See [Issue #679](https://github.com/websharks/comet-cache/issues/679).

**Comment by raamdev** [comment]
**Comet Cache v160227** has been released and includes changes from this GitHub Issue. See the [v160227 announcement](https://cometcache.com/blog/comet-cache-v160227-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#679).
