### ISSUE TITLE
Suggestion: Have a "Save Changes" button on the "Plugin Updater" page

### ISSUE THREAD

**Issue by bridgeport** [wpsharks/comet-cache#681]
As far as I can tell, there's no way to change save settings (e.g., username, license key, dashboard notifications, beta testers) without also forcing an update.

For instance, going from ZenCache Pro to Come Cache Pro results in a new license key to be updated. When saving the new license key, the Update button will re-download the same installed version, remove the existing, then reinstall.

A save button would resolve this and changes to any of the other minor settings.

Thanks.

**Comment by jaswrks** [comment]
:+1:

**Comment by theperfectwill** [comment]
@jaswsinc +1 for this. 

To add, I would like to mention while this thought is up... 

I've always needed a save changes button at the top of the plugin settings page. 

I personally loathe having to scroll all the way down to the end of the plugin's settings page to save a change, especially when that setting change is simple as turning the plugin on or off at the top of the page, then having to scroll all the way down to save that change.

Thoughts on that? 

My thoughts on it:
- I would like a save changes button at the top. 
- I think a big save changes button would may be be too much at the top? (not sure)
- Maybe a smaller save changes button near the "Restore" and "Clear" button area? (not sure, just a thought)
- Screenshot reference @ http://take.ms/rD60a

**Comment by raamdev** [comment]
@bridgeport Yes, I totally agree. Thank you for posting this! I've noticed the lack of a Save Changes button the Pro Updater plugin to be quite annoying but I kept forgetting to open a GitHub issue so that we could get that fixed. :-)

@NoahjChampion I also totally agree with you. I've experienced the same frustration of having to scroll all the way to the bottom to hit the Save All Changes button whenever I'm making changes in a panel at the top. 

We've discussed a bit internally about revamping the entire plugin options panel UI a bit to organize things better and make things the Save All Changes button more user-friendly, so it's possible this work could be part of that. If we don't get around to a larger UI revamp soon, adding the Save All Changes button to the Plugin Updater page, and at the top of the main options page, would be pretty simple.

**Comment by theperfectwill** [comment]
@raamdev ok. This sounds good. 

Going into a new revamp, not sure what ideas you have about it, wether off a framework or not, but it would also be a better experience I feel if the Panel Headings "plugin-menu-page-panel-heading" would collapse when another panel heading is opened. The content in each panel heading is so detailed focused, I don't think there is much use to have multiple ones open at once? I know for me, there isn't and usually to not make the page extensively long, I have to collapse every panel heading I open so it doesn't make the scroll page longer. This can add a lot of extra unneeded clicks just to avoid scrolling down a long page, which is also (now) because of the only save button being at the bottom of the page. 

But this also brings up the idea I had of a "Toggle All" or "Open All" and "Close All" option to control the panel headings at once. 

Thoughts?

**Comment by raamdev** [comment]
> But this also brings up the idea I had of a "Toggle All" or "Open All" and "Close All" option to control the panel headings at once.

@NoahjChampion That already exists, but you're not the first one to miss that the plugin already has this... @jaswsinc added that part of the UI a _long_ time ago, and I missed that it was even there for the longest time!

![2016-02-25_11-30-15](https://cloud.githubusercontent.com/assets/53005/13326272/318d9a62-dbb3-11e5-8601-713b7330eb49.png)

---

Thanks for the other feedback. Referencing https://github.com/websharks/comet-cache/issues/96, which is the issue specifically for improving the overall interface. I'll post some mockups on that GitHub issue when we start working on this, so I suggest subscribing to that issue to stay updated--I'd LOVE feedback on any UI changes we propose. :-)

**Comment by theperfectwill** [comment]
@raamdev Wow... I never saw that either :(

Thanks for that and I will look out for the UI conversations. I'm actually subscribed to everything of Comet Cache :)

**Comment by raamdev** [comment]
![2016-04-08_13-31-12](https://cloud.githubusercontent.com/assets/53005/14392204/31554890-fd8e-11e5-8525-5cd602ef4f99.png)

**Comment by raamdev** [comment]
Next Release Changelog:
- **UI/UX Enhancement** (Pro): The Pro Plugin Updater page now includes a "Save All Changes" button at the bottom, allowing you to save changes to the updater configuration without actually running the plugin updater. Props @bridgeport @NoahjChampion @1wdtv. See [Issue #681](https://github.com/websharks/comet-cache/issues/681).

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#681).
