### ISSUE TITLE
Backwards compatibility for Quick Cache __advanced_cache is missing

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#710]
_Originally reported here: https://wordpress.org/support/topic/backwards-compatibility-with-oldquickcache-advanced-cache-plugins-is-broken?replies=1_

---

It appears that we missed backwards compatibility for `quick_cache__advanced_cache` in the `advanced-cache.txt` template: https://github.com/websharks/comet-cache/blob/160227/src/includes/templates/advanced-cache.txt#L221-L226

All we should need is the following added to that file:

``` php
if (!isset($GLOBALS['quick_cache__advanced_cache'])) {
    $GLOBALS['quick_cache_advanced_cache'] = &$GLOBALS[GLOBAL_NS.'_advanced_cache'];
    $GLOBALS['quick_cache__advanced_cache'] = &$GLOBALS[GLOBAL_NS.'_advanced_cache'];
}
```

Do you concur @jaswsinc?

**Comment by raamdev** [comment]
@jaswsinc Ping. ↑

**Comment by jaswrks** [comment]
I just reviewed the codebase again. Yes, that should to it. I had doubts that it would, because themes like Weaver II that integrated with this were also dependent upon old Quick Cache hook names (or so I thought), but as it turns out the hook name we suggested was prefixed with `get_class($this)`, which is dynamic enough that if they followed that suggestion, the change you have above should do the job.

**Comment by jaswrks** [comment]
> It appears that we missed backwards compatibility for quick_cache__advanced_cache in the advanced-cache.txt template: https://github.com/websharks/comet-cache/blob/160227/src/includes/templates/advanced-cache.txt#L221-L226

Just to confirm, we are not supporting Quick Cache backward compat in Comet Cache, right? This particular issue can be resolved easily, which is what I think you're trying to do since it is simple. However, moving forward we aren't trying to support the old Quick Cache hook names/filters/constants/globals etc. Do I have that right?

**Comment by raamdev** [comment]
> This particular issue can be resolved easily, which is what I think you're trying to do since it is simple. However, moving forward we aren't trying to support the old Quick Cache hook names/filters/constants/globals etc. Do I have that right?

Yes, that's correct.

**Comment by raamdev** [comment]
Next Release Changelog:
- **Compatibility**: Fixed a compatibility issue for some themes and plugins that were using old AC Plugin code designed to work with Quick Cache. This fix adds some backwards compatibility support for Quick Cache, but note that the first release of Comet Cache dropped support for Quick Cache backwards compatibility in favor of ZenCache backwards compatibility. See [Issue #710](https://github.com/websharks/comet-cache/issues/710).

**Comment by raamdev** [comment]
**Comet Cache v160416** has been released and includes changes from this GitHub Issue. See the [v160416 announcement](https://cometcache.com/blog/comet-cache-v160416-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#710).
