### ISSUE TITLE
Can't update Comet Cache Pro (Unknown error)

### ISSUE THREAD

**Issue by ryanmount** [wpsharks/comet-cache#717]
Getting "Unknown error. Please wait 15 minutes and try again" when trying to update Comet Cache.

**Comment by raamdev** [comment]
@ryanmount There is already an issue open for this; please see https://github.com/websharks/comet-cache/issues/678. 

The issue is that your server is running an outdated version of cURL that is not compatible with our update servers. We recommend asking your web hosting company to update to cURL v7.36+ to resolve this issue. Earlier versions of cURL do not support newer security technologies and cURL v7.36 was released 2 years ago, so it's time to upgrade.
