### ISSUE TITLE
Feature Request: Caching redirects by redirection plugins

### ISSUE THREAD

**Issue by GermontZ** [wpsharks/comet-cache#722]
Hello!
After installing a redirect plugin, I understood that every redirected link require a few additional queries to the database, which means more waiting time. I suppose that would be more practical to cache these redirects, even forever if we want it, in a separate cache which is never cleared when the usual cache is deleted.
I also wonder if this solve the case when there is no connection with database.

**Comment by jaswrks** [comment]
Which redirection plugin are you using?

**Comment by GermontZ** [comment]
This one https://wordpress.org/plugins/redirection/

**Comment by jaswrks** [comment]
Thank you. Does that plugin give you the ability to choose the status code that is used for the redirection? If so, I recommend using 301 redirects, because those get cached automatically by most browsers, which will speed things up just a bit for you. http://stackoverflow.com/a/21396547/1219741

Having said that, I do agree that it would be nice if Comet Cache could cache these. Currently, they are not, because there is no output during a redirection, and Comet Cache will simply not cache an empty output buffer at this time. We could look into improving that behavior though.

@raamdev Thoughts on this?

---

@GermontZ also writes...

> I also wonder if this solve the case when there is no connection with database.

Hmm, I'm not sure what you mean by this. Can you elaborate just a bit further please?

**Comment by raamdev** [comment]
@jaswsinc writes...

> Thoughts on this?

Hmm, it sounds like an interesting idea. However, I think any support for redirection plugins should probably be explicit, i.e., we add support for several specific redirection plugins. I'm not seeing an easy way to make this reliable otherwise. (What determines a "redirection" that should be cached?) 

Another reason I would want to add per-plugin support is that it's pretty important that when a redirect target is changed in the Dashboard, that the redirect cache be cleared so that the redirect starts going to the new target. Otherwise, the redirect would continue being sent to the old location. Again, the only way I can see us detecting changes and updating the redirect cache reliably is to build support for specific redirection plugins.

**Comment by jaswrks** [comment]
> Hmm, it sounds like an interesting idea. However, I think any support for redirection plugins should probably be explicit, i.e., we add support for several specific redirection plugins. I'm not seeing an easy way to make this reliable otherwise. (What determines a "redirection" that should be cached?)

Yep, great points.

I was thinking that a 301 (permanent) redirect would qualify it as being cacheable; i.e., if we can detect that a request was processed with a 301 status and a `location:` header, then that would be something we could cache in order to prevent repeat DB lookups on each future redirection. That would help plugins like our own WP Redirects also.

> Another reason I would want to add per-plugin support is that it's pretty important that when a redirect target is changed in the Dashboard, that the redirect cache be cleared so that the redirect starts going to the new target. Otherwise, the redirect would continue being sent to the old location. Again, the only way I can see us detecting changes and updating the redirect cache reliably is to build support for specific redirection plugins.

Yep, good point. That could get tricky.

**Comment by GermontZ** [comment]
_I also wonder if this solve the case when there is no connection with database._

> Hmm, I'm not sure what you mean by this. Can you elaborate just a bit further please?

I am saying that sometimes the visitor can't view the page, either because it can't be loaded from the database, or it can't be redirected to the actual url if it's required. What about the case if a page is already cached as html and also have its redirection cached? Could the visitor still load the page?

Thanks both of you for answers, it seems you really enjoy what you do!

**Comment by jaswrks** [comment]
> I am saying that sometimes the visitor can't view the page, either because it can't be loaded from the database, or it can't be redirected to the actual url if it's required. What about the case if a page is already cached as html and also have its redirection cached? Could the visitor still load the page?

Hmm. I'm still not sure that I completely understand. It sounds like the question you're asking might be plugin-specific; i.e., have more to do with the redirection plugin than with Comet Cache?

**Comment by GermontZ** [comment]
My point is if the site could still be online using a cache plugin, even if there is no connection with database. After all, the html is there, also the redirection.

**Comment by raamdev** [comment]
> My point is if the site could still be online using a cache plugin, even if there is no connection with database. After all, the html is there, also the redirection.

That would require a pure Apache-rewrite method, i.e., no interaction whatsoever with WordPress (which requires the database). The primary (and currently the only) method used by Comet Cache for loading the caching system requires the `advanced-cache.php` file, which is loaded by WordPress very early on. That is what Comet Cache (and most other WordPress caching plugins) use. 

Using Apache-only for caching gives up a lot of control (and therefore a lot of the intelligence) that Comet Cache needs to ensure that cache files remain up-to-date, which is why it hasn't been a priority. However, we have plans to explore additional caching methods, such as Apache ModRewrite, which would allow you to avoid WordPress and PHP (and therefore the database) altogether.

**Comment by GermontZ** [comment]
Thanks for a detailed answer, now I am enlightened :)  I will do my best to extend my Pro licence if you add apache rewrite. Well, just one more reason to do it.
