### ISSUE TITLE
Static CDN Filter broken login page

### ISSUE THREAD

**Issue by anchantw** [wpsharks/comet-cache#730]
When Static CDN Filter is active and logout, login page is broken.
After filter is on, access login page and check web source, I found the following code, 
http://cdn.example.com/wp-admin/css/login.min.css.
Normally no need to change CDN "wp-admin" folder, right?

**Comment by jaswrks** [comment]
@anchantw writes...

> http://cdn.example.com/wp-admin/css/login.min.css.

I just tested this myself and I was unable to reproduce that behavior in a clean WordPress installation. However, I suspect this _could_ be happening on your end due to the way that specific URL is being formulated. Do you know which theme or plugin is introducing that `login.min.css` file? If so, does it use `admin_url()` to construct the link or does it use `home_url()` or `site_url()` to build the link?

**Comment by raamdev** [comment]
Closing due to lack of feedback.
