### ISSUE TITLE
Feature Request: Multisite Exclusion Patterns

### ISSUE THREAD

**Issue by kristineds** [wpsharks/comet-cache#754]
It would be nice if we could add a new Comet Cache Option panel for Multisite networks that would allow a network admin to exclude Comet Cache from certain sub-sites.

---

Requested here: [private internal ticket](https://websharks.zendesk.com/agent/tickets/12266)

**Comment by jaswsinc** [comment]
👍

**Comment by jaswrks** [comment]
## Next Actions
- Before [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/classes/Plugin.php#L365) add the following:
  
  ``` php
  'exclude_hosts' => '', // Empty string or line-delimited patterns.
  ```
- Before [this line](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Plugin/InstallUtils.php#L312) add the following:
  
  ``` php
  case 'exclude_hosts': // Converts to regex (caSe insensitive).
  ```
- Before [this block of code](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/templates/advanced-cache.txt#L178-L187) add this new block:
  
  ``` php
  if (!defined('COMET_CACHE_EXCLUDE_HOSTS')) {
      /**
       * Host exclusions.
       *
       * @since 16xxxx Adding host exclusions.
       *
       * @var string A regular expression; else an empty string.
       */
      define('COMET_CACHE_EXCLUDE_HOSTS', '%%COMET_CACHE_EXCLUDE_HOSTS%%');
  }
  ```
- Before [this block of code](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Ac/ObUtils.php#L161-L163) add the following new block:
  
  ``` php
  if (COMET_CACHE_EXCLUDE_HOSTS && preg_match(COMET_CACHE_EXCLUDE_HOSTS, $_SERVER['HTTP_HOST'])) {
      return $this->maybeSetDebugInfo($this::NC_DEBUG_EXCLUDED_HOSTS);
  }
  ```
- Before [this block of code](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/interfaces/Shared/NcDebugConsts.php#L195-L202) add the following new block:
  
  ``` php
  /**
  * No-cache because the current request is excluded by its host name.
  *
  * @since 16xxxx Host exclusions.
  *
  * @type string A unique string identifier in the set of `NC_DEBUG_` constants.
  */
  const NC_DEBUG_EXCLUDED_HOSTS = 'nc_debug_excluded_hosts';
  ```
- Before [this block of code](https://github.com/websharks/comet-cache-pro/blob/160417/src/includes/traits/Ac/NcDebugUtils.php#L166-L168) add the following new block:
  
  ``` php
  case $this::NC_DEBUG_EXCLUDED_HOSTS:
      $reason = __('because `$_SERVER[\'HTTP_HOST\']` matches a configured Host Exclusion Pattern on this installation.', SLUG_TD);
      break; // Break switch handler.
  ```
- Add a new UI config panel with the title "Host Exclusion Patterns". This should be available in both the lite and pro versions of the software, but only shown if `is_multisite()`; i.e., only for Network installations that may have more than a single host that needs to be cached.
  
  In addition, add a filter so that this panel can be shown on standard WP installations in special cases.
  
  ``` php
  if ($this->plugin->applyWpFilters(GLOBAL_NS.'_exclude_hosts_option_enable', is_multisite())) {
      // Display option panel for Host Exclusion Patterns.
  }
  ```
  
  _**Time-saver:** This panel should appear just before URI Exclusion Patterns and you should be able to copy that existing panel and then adapt it for Host Exclusion Patterns. It will be nearly identical._
  
  ![2016-05-12_05-38-34](https://cloud.githubusercontent.com/assets/1563559/15216621/4da4bfea-1804-11e6-9314-b46e3192728c.png)

**Comment by jaswrks** [comment]
> It would be nice if we could add a new Comet Cache Option panel for Multisite networks that would allow a network admin to exclude Comet Cache from certain sub-sites.

It's also worth noting that URI Exclusion patterns that already exist in Comet Cache can be used to exclude certain child sites if the network uses sub-directories instead of sub-domains.

A MS Network installation can be configured in one of two ways:
- main.com`/child-blog/`
- `child-blog`.main.com

## Via URI Exclusion

``` txt
^/child-blog/**
```

## Via Host Exclusion (Coming Soon)

``` txt
^child-blog.*$
```

**Comment by raamdev** [comment]
![2016-06-24_14-29-51](https://cloud.githubusercontent.com/assets/53005/16346969/20f5f00a-3a18-11e6-95fe-28f001fa6e07.png)

**Comment by raamdev** [comment]
Next Release Changelog:
- **New Feature!** Multisite Host Exclusion Patterns. It's now possible to exclude entire sites from the cache in a Multisite Network environment. Domain mapping is also supported! See _Comet Cache → Plugin Options → Host Exclusion Patterns_. If you're running a Multisite Network with Sub-Directories, you can exclude sites using the existing URI Exclusion Patterns feature. Props @kristineds. See [Issue #754](https://github.com/websharks/comet-cache/issues/754).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#754).
