### ISSUE TITLE
mysqli_query(): Error reading result set's header in wp-db.php

### ISSUE THREAD

**Issue by benoitchantre** [wpsharks/comet-cache#758]
When I turn enable Comet Cache, I can see a lot of these warnings in the server logs
When I turn disable Comet Cache, I see no new warnings like these.

I think they started to happen after the upgrade to WordPress 4.5

```
[Thu May 05 00:37:42 2016] [error] [client 128.65.195.34] FastCGI: server "/home/clients/b9bea0796c13d5f0e5012c76b5730384/.config/apache/mydomain.com/.fpm/php5.external" stderr: PHP message: PHP Warning: mysqli_query(): Error reading result set's header in /home/clients/b9bea0796c13d5f0e5012c76b5730384/web/_wp/wp-includes/wp-db.php on line 1811
```

```
[Thu May 05 05:54:48 2016] [error] [client 128.65.195.34] FastCGI: server "/home/clients/b9bea0796c13d5f0e5012c76b5730384/.config/apache/mydomain.com/.fpm/php5.external" stderr: PHP message: PHP Warning: mysqli_query(): MySQL server has gone away in /home/clients/b9bea0796c13d5f0e5012c76b5730384/web/_wp/wp-includes/wp-db.php on line 1811
```

**Comment by raamdev** [comment]
@benoitchantre I did some research and it appears that this is not specific to Comet Cache: there has been an increase in reports of that error by lots of WordPress site owners after upgrading to WP 4.5. It just so happens that, in your case, Comet Cache is what's triggering the issue. The issue has to do with your MySQL server configuration. 

I suggest contacting your web hosting company to see if they can look at the server logs for more information.

See also: 
- http://stackoverflow.com/questions/11583352/php-mysql-server-has-gone-away
- http://stackoverflow.com/questions/1644432/mysql-server-has-gone-away-in-exactly-60-seconds

**Comment by benoitchantre** [comment]
@raamdev For information, the host said the connexion with mysql is closed after 30 seconds when it doesn't receive any request. If I want to remove the warnings, I can either ping the server frequently or to test if the connexion still exist and if not to reconnect. I think it will be patched in WordPress.

**Comment by raamdev** [comment]
@benoitchantre Great! Thank you for the update. I'll go ahead and close this issue here then since this doesn't appear to be specific to Comet Cache. :-)

**Comment by benoitchantre** [comment]
There's now a [ticket on trac](https://core.trac.wordpress.org/ticket/36869).

**Comment by jaswrks** [comment]
@benoitchantre I have seen that same sort of behavior myself in rare instances where some other plugin delays reading/writing to an open MySQL connection. In those cases, I had my hosting company resolve the problem by adjusting the MySQL `wait_timeout` config option. See: http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

**Comment by jaswrks** [comment]
Note that `wait_timeout` impacts the following
scenario that can occur all in a single process lifecycle.
- WordPress loads initially.
- WordPress connects to MySQL initially w/o issue.
- Another plugin runs and does something that takes X number of seconds longer than expected.
- The plugin is done now, and WordPress continues doing it's thing.
- WordPress, now able to continue, attempts to perform a DB query as usual.
- 🐛  ... Ugh! The plugin took so long that MySQL decided to leave the party, and now you get the error that says MySQL has gone away. The plugin is to blame for taking too long, but also, `wait_timeout` might be so short that any minor interruption to what would be considered a _normal_ PHP process can lead to this mysterious problem; i.e., `wait_timeout` is too short.

### Solution

Increasing `wait_timeout` (slightly) resolves the issue.

**Comment by benoitchantre** [comment]
@jaswsinc Thanks for the details about this issue.
I have added `@ini_set('mysql.connect_timeout', 300);` to my wp-config.php to see if the warnings disappear. The default timeout set by the host is 30 seconds.

**Comment by jaswrks** [comment]
Copy that. I hope that resolves the problem for you.

However, my feeling is that it won't, because the error that you reported was, "_MySQL server has gone away_". That specific error is an indication that the connection succeeded, but then MySQL went away; i.e., broke the connection due to `wait_timeout`. Altering `connect_timeout` is not likely to resolve this, because if connections were failing you would be seeing different errors and it's also likely that those would occur far more often in that case.

**Comment by jaswrks** [comment]
> When I turn enable Comet Cache, I can see a lot of these warnings in the server logs

The combination of things that you've reported confirms my suspicion that this is due to MySQL `wait_timeout`. However, since you also pinpointed Comet Cache as a factor that impacts this behavior, that suggests that Comet Cache is the plugin taking longer than expected in the [lifecycle I mentioned previously](https://github.com/websharks/comet-cache/issues/758#issuecomment-219851485).

For that reason, when debugging this issue I would also be sure to do a careful review of the drive that Comet Cache is writing cache files to. If cache file generation and disk writes are taking longer than expected, that could be the whole reason you're hitting MySQL `wait_timeout`.

Reasons for slow disk writes by Comet Cache can include:
- Your configured cache directory is full.
- Or, your configured cache directory is writing to a network-based file system that actually requires data to be transferred to a remote destination instead of being written locally.
- The hard drive performance is degrading; i.e., drive is perhaps going to fail in the near future.

**Comment by jaswrks** [comment]
Also, the HTML Compressor can cause this too, as it takes much longer to run than Comet Cache running on it's own. If you currently have the HTML Compressor running, try turning that off and see if it makes any difference. If you currently have the HTML Compressor running and you're seeing "MySQL server has gone away", I'd call that the most obvious culprit.

**Comment by benoitchantre** [comment]
> Altering connect_timeout is not likely to resolve this, because if connections were failing you would be seeing different errors and it's also likely that those would occur far more often in that case.

You are right ; my test with `@ini_set('mysql.connect_timeout', 300);` didn't solved the issue.
I have removed it.

> Reasons for slow disk writes by Comet Cache can include:
> - Your configured cache directory is full.
> - Or, your configured cache directory is writing to a network-based file system that actually requires data to be transferred to a remote destination instead of being written locally.
> - The hard drive performance is degrading; i.e., drive is perhaps going to fail in the near future

The issue is probably not related to slow disk writes : 
- the cache directory is set to wp-content/cache/comet-cache (default)
- there's only 550 Mo used 100 Go available
- hard drives have been replaced by SSDs by the host at the end of last year

Here are some values from Query Monitor (logged out of WordPress, Comet Cache disabled) for an archive page.
- Page generation time : 0,4533 (1,5% of 30s limit)
- Peak memory usage : 27 546 kB (10,5% of 262 144 kB limit)
- Database query time : 0,2354
- Database queries : SELECT: 175, SHOW: 3

Here are some infos about the options I have enabled in Comet Cache Pro
- Cache Directory : .../wp-content/cache/comet-cache (default)
- Cache Expiration Time : 30 days
- Cache Cleanup Schedule : 1 hour
- Disable Cache Expiration if Server Load Average is High : not set
- Get Requests : do not cache
- 404 Requests : do not cache
- Auto-Cache Engine : enabled, based on a sitemap
- Auto-Cache Delay Timer : 500 (milliseconds)
- HTML Compression : do not compress

I'm now testing with Auto-Cache disabled.

**Comment by benoitchantre** [comment]
With Auto-Cache disabled, I have no more warnings.
Now, I'm trying different values for Auto-Cache Delay Timer. With a value of `2000`, I see warnings again.

Maybe the delay timer parameter doesn't work properly: I have tested with a value of `5000`, and when I manually refresh the stats/charts multiple times in 5 seconds, I can see that many news files are cached.

With a value of `10000`, I see approximatively 1 file cached per second.

With Auto-Cache enabled and a delay timer of `10000`, the warning change to

```
[Wed May 18 08:30:00 2016] [error] [client 128.65.195.34] FastCGI: server "/home/clients/b9bea0796c13d5f0e5012c76b5730384/.config/apache/mydomain.com/.fpm/php5.external" stderr: PHP message: PHP Warning: Error while sending QUERY packet. PID=23695 in /home/clients/b9bea0796c13d5f0e5012c76b5730384/web/_wp/wp-includes/wp-db.php on line 1811
```

**Comment by benoitchantre** [comment]
@raamdev it seems there's a bug with the Auto-Cache Engine.

**Comment by raamdev** [comment]
@benoitchantre This does not look like a problem with Comet Cache but a problem with your MySQL server configuration. 

```
PHP Warning: Error while sending QUERY packet.
```

That error is related to database communication. The Auto-Cache Engine does not even make database queries—its sole job is to read your XML Sitemap URL and then make HTTP connections to each URL in the sitemap (so that each URL can be cached by Comet Cache).

**Comment by jaswrks** [comment]
> Error while sending QUERY packet. PID=23695

I agree with @raamdev. That looks more like a MySQL load/performance issue. Generally speaking, if you're seeing that error (especially if you think it's somehow associated with the Auto-Cache Engine), then it could be an indication that your MySQL server is working too hard. Or, it could be that you have a rogue plugin making very large database queries; i.e., with very large packets.

#### Some things to look at:
- Does increasing the resources available to MySQL avoid this problem? If so, it might be time for a server upgrade. MySQL is a driving factor behind WordPress, so giving MySQL enough memory, CPU, and tuning your configuration may go a long way.
- Or, is MySQL simply working too hard for a site of your size? I'd start by tuning Comet Cache just a bit. If your site has limited resources, set the Comet Cache Auto-Cache Delay Timer to: `2000` instead of the default `500` and see if that helps. If the Auto-Cache Engine is making repeated connections without enough of a delay, it could be stressing your server. Normally, `500` milliseconds is enough of a delay, but if your server has very limited resources, increasing this delay could help you.
- Also remove other plugins from the equation to help you isolate the issue. For instance, anything other than Comet Cache can be removed to see if that clears up the issue. Then add one plugin back in at a time until the problem comes back; i.e., identify the rogue plugin.

**Comment by raamdev** [comment]
As a follow-up to Jason's last point, here's a good article to review: [Testing Comet Cache in a Clean WordPress Installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/)
