### ISSUE TITLE
Hey folks...want to report this on HTML Compression but where categories/content not showing up

### ISSUE THREAD

**Issue by gwfc** [wpsharks/comet-cache#776]
With this on http://screencast.com/t/Pgr4fTFo4uPw

The list of categories excerpts are on the page but hidden from view for logged out users (effectively showing a blank page to people who are logged out).

For logged in users, the are fine and work and can be seen.

When I disable http://screencast.com/t/Pgr4fTFo4uPw then categories excerpts are seen perfectly for logged out and logged in users.

Is there a sub section I can disable to temporarily be able to generally use html compress for now but disable one or more sub sections until you guys can roll out a fix OR do I have to leave it totally off for the fix?

FYI, when html compress is off/disabled is if fine showing category content like this http://screencast.com/t/jWUuWdxJP
and when it is on the pages are totally blank like this http://screencast.com/t/yq5FTgAizDk6 (no content at all)

Let me know what you think and if this is helpful so a fix can be rolled out at some point (soon hopefully).

NOTE: Here is the Inspect element errors too FYI http://screencast.com/t/iFdRDaztG (when content does not render)...not present when there is content and HTML Compression overall is just disabled.

:)

. . . . UPDATE: I just turned this subset OFF only and it seems to be working (for now): http://screencast.com/t/VWMfBleHN (should I turn off any other elements too that could be related to the Inspect element here http://screencast.com/t/iFdRDaztG ? But, I can tell you I do not see those errors now either.

**Comment by raamdev** [comment]
@gwfc Not all themes/plugins are compatible with HTML Compression, so you may need to turn off certain HTML Compression features or exclude certain scripts from being compressed. Otherwise, you'll need to get in touch with the developer of the problematic theme/plugin and work with them to make it compatible with compression. 

Also, we reserve GitHub for filing bug reports and making feature requests. Please post support questions to the [Community Forum](https://cometcache.com/r/community-forum/) (for Comet Cache Lite) or open a [Support Ticket](https://www.websharks-inc.com/support/?product=comet-cache&request_type=trouble_ticket) (Comet Cache Pro). Thank you! 😃
