### ISSUE TITLE
Enhancement: Clarify the use of Full URLs in inline docs for Misc. Auto-Clear Options

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#781]
Under **Automatic Cache Clearing → Misc. Auto-Clear Options**

It would be great to explain that a single URL must be complete including `https/http` and domain.

![screen shot 2016-05-26 at 3 26 16 pm](https://cloud.githubusercontent.com/assets/13220018/15567127/2300492c-2357-11e6-9834-6c5f3e5cf50f.png)

Some users were under the impression relative links for single URLs could be used. e.g. `/name-of-post`, this does not work for single URLs. The full URL must be input on the line for it to auto-clear correctly.

**Comment by jaswrks** [comment]
The intended functionality is for this to require a full URL so that a host can be considered as well, or even the scheme, which may (at times) be desirable; e.g., to only clear the `https://` cache or to only clear the cache for a particular domain that you're using.

However, I do agree that in most cases the full URL is not necessary and it seems like it would be worth it for us to somehow support a URI (partial URL). On that note though, it's just as easy to use a wildcard for this. e.g., `*/category-abc/*` works without needing to enter the full URL.

**Comment by raamdev** [comment]
@jaswsinc writes...

> On that note though, it's just as easy to use a wildcard for this. e.g., _/category-abc/_ works without needing to enter the full URL.

Does it? I would think that would need to be `**/category-abc/*`, where the `**` would include the slashes in the scheme (e.g., `http://`).

**Comment by raamdev** [comment]
@jaswsinc Actually, I just tested this and neither `*/category-abc/*` nor `**/category-abc/*` worked. I had to enter the full first part of the URL to get it to clear the URL: `http://example.com/category-abc/*`

**Comment by jaswrks** [comment]
Oh, I'm so sorry. I was mistaken. Yep, I can see [from this method](https://github.com/websharks/comet-cache-pro/blob/160521/src/includes/traits/Shared/CachePathUtils.php#L279) that a full URL is required by this routine, because it currently depends on `buildCachePath()` which expects a parseable URL. So while the wildcards work in the inner portions of the URL, they won't make it past the `parse_url()` function if it, for example, starts with `**/`. Bummer.

**Comment by jaswrks** [comment]
> Does it? I would think that would need to be *_/category-abc/_, where the *\* would include the slashes in the scheme (e.g., http://).

Yes, you are correct there also. Very sorry for the confusion.

**Comment by raamdev** [comment]
Next Release Changelog:
- **UX Enhancement**: Improved the inline docs for Auto-Clear List of Custom URLs to clarify that full URLs must be provided. Props @renzms. See [Issue #781](https://github.com/websharks/comet-cache/issues/781).

**Comment by raamdev** [comment]
**Comet Cache v160706** has been released and includes changes from this GitHub Issue. See the [v160706 announcement](https://cometcache.com/blog/comet-cache-v160706-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#781).
