### ISSUE TITLE
Updates - Non-standard

### ISSUE THREAD

**Issue by bobo1** [wpsharks/comet-cache#804]
I consider this a bug - We have dozens of sites using cometcache. I like the plugin. However, the updating process is a pain. We use managewp, and ithemes sync to update and monitor our sites. Yours in the only plugin that we have to go into each site and update manually. You need to use the standard WP process so this is easier. Please advise. It's really becoming a major issue.

**Comment by raamdev** [comment]
@bobo1 We already have a GitHub issue open for ManageWP; see https://github.com/websharks/comet-cache/issues/465. Please leave an update there instead of opening a new GitHub issue so that your vote can be added to the existing issue.

I'm adding ManageWP to the Next Release milestone so that we can hopefully get that worked into the next release.
