### ISSUE TITLE
This is wrong!

### ISSUE THREAD

**Issue by uhlhosting** [wpsharks/comet-cache#815]
So you are telling me since my Woocommerce login button is on all pages at all times, and that is a must for wponce, then you tell me none of this site would ever be cached or I will cache it but breach security rules, how stupid is that... This is simply worthless, and the fact that you close all my tickets without giving me a chance to discuss the issue, is very unprofessional! I am here for help, not for rejection or for ruffless answers. Again how do I solve this, without having to face security issues? Otherwise the plugin for me is useless, and I bet I am not the only one who uses the Woocommerce with wordpress that would like his pages cached.

**Comment by raamdev** [comment]
@highacid I'm closing your **GitHub Issues** (not tickets—if you're a Pro customer, please [open a ticket](https://cometcache.com/support/)) because we don't provide support on GitHub. You're asking for support. You've open two other GitHub issues (https://github.com/websharks/comet-cache/issues/813 and https://github.com/websharks/comet-cache/issues/814) and I have repeatedly pointed you to the relevant KB article. 

>  then you tell me none of this site would ever be cached or I will cache it but breach security rules

[The KB article](https://cometcache.com/kb-article/what-are-wordpress-nonces-and-why-are-they-not-cache-compatible/) clearly explains what the risk is: "if you choose to enable nonce caching globally, then a visitor to your site could be served a cache file generated by another visitor that contains a nonce value intended for someone else. That's opening the door for potential security issues."

We're working to improve the ability to cache nonces, **but only for Logged-In Users**; see https://github.com/websharks/comet-cache/issues/793. As stated in the KB article I linked to above, caching nonces for anonymous visitors is not a good idea. You can do it (and the KB article explains how), but we don't recommend it.
