### ISSUE TITLE
Mod_Security Rule 340163 Still an Issue with Comet Cache Pro Updater

### ISSUE THREAD

**Issue by seozones** [wpsharks/comet-cache#816]
I'm still having issue with automatically updating the plugin (now called Comet Cache). The webhost called hostnine.com is saying the issue is with the rule #340163

Here is the full mod_sec hit:

[Sat Aug 13 19:28:11 2016] [error] [client 73.14.198.125] ModSecurity: Access denied with code 403 (phase 2). Match of "rx ://%{SERVER_NAME}/" against "ARGS:comet_cache_update_pro_zip" required. [file "/usr/local/apache/conf/mod_sec/mod_sec.asl.conf"] [line "547"] [id "340163"] [rev "289"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Remote File Injection attempt in ARGS (MM)"] [data "cometcache.com/?tsl=eerWD"] [severity "CRITICAL"] [hostname "domain-hidden.com"] [uri "/wp-admin/update.php"] [unique_id "V6@tC4F5sUwAAAndcCEAAAAQ"]

Any permanent fix to this? I have like 50 sites using this plugin and I don't want to update it manually on each one.

**Comment by raamdev** [comment]
@seozones Thanks for the feedback. It looks like the work we did in https://github.com/websharks/comet-cache/issues/416 did not solve the issue like we expected it to. 

Would it be possible to get a copy of that ModSecurity rule so that I can set up a test environment and attempt to replicate this?

**Comment by seozones** [comment]
Okay I’ll have to ask the host.

**Comment by raamdev** [comment]
Closing due to lack of feedback.
