### ISSUE TITLE
Unable to publish from Adobe Lightroom to Envira Gallery

### ISSUE THREAD

**Issue by midiman369** [wpsharks/comet-cache#841]
Hi,

I have been troubleshooting an issue with the Envira Gallery plugin's Lightroom Plugin which utilizes the WP Rest API v2 / JSON to publish photo galleries directly to Wordpress from Adobe Lightroom.

After some testing it was concluded that when Comet Cache is enabled, the Envria Gallery Lightroom Plugin is not able to publish to the site.

I tried adding the relevant URL's to the URI Exclusion Patterns list, but it does not seem to make any difference. I am only able to publish to the site when I deactivate the entire Comet Cache plugin.

Please let me know what steps I can take to begin troubleshooting this particular issue.

Thank you!
Andrew

Received reply to post issue on GitHub:

> (WebSharks™ Support Center)
> Oct 10, 10:23 PM EDT
> 
> Hi Andrew! :-)
> 
> Thanks for reporting. If you can open an official bug report here and include a link to download this plugin, along with step-by-step instructions that show us how to reproduce this issue on our side it would be really helpful. See: https://github.com/websharks/comet-cache/issues/new

The Envira Gallery plugin and addons may be downloaded through enviragallery.com  I am not sure if I am able to directly provide download links for the plugin / lightroom addon as it is a paid plugin and requires license/activation.  I realize this may be a complicated issue to troubleshoot because of this.  Please let me know how I may assist.

Steps to reproduce:
1. Install Wordpress Envira Gallery Plugin with Adobe Lightroom addon, dependency addons, WP Rest API v2 wordpress plugin, and configure with Comet Cache Pro plugin activated on site.
2. Install Envria Gallery Plugin for Adobe Lightroom into Adobe Lightroom (not to be confused with the addon/plugin for the Wordpress Site).
3. Configure Adobe Lightroom plugin with keys generated from Envira Gallery on wordpress site.
4. Attempt to create and publish a collection from Lightroom to the Envira Gallery.  Receive errors in Lightroom.
5. Deactivate Comet Cache on site and try again.  Works, am now able to successfully publish a collection from Lightroom to Wordpress.

**Comment by raamdev** [comment]
> Receive errors in Lightroom.

@midiman369 Can you tell me what errors you receive in Lightroom?

I can't think of any reason Comet Cache would cause problems here, although I admit we haven't done any extensive testing with the new WP REST API.

**Comment by midiman369** [comment]
Hi,

Here is the error that appears from Lightroom when trying to publish with the Comet Cache Pro plugin activated.

```
Can’t update this collection.
An internal error has occurred: AgExportSession:recordRemoteCollectionId: remote ID must be a number or string
```

**Comment by raamdev** [comment]
@midiman369 Have you tried contacting Koken support to see if this is maybe a bug in the plugin? See [this thread with similar bug reports](http://help.koken.me/customer/portal/questions/8387421-koken-lightroom-publish-plugin-error). I realize that you said disabling Comet Cache seems to fix the issue, but that might just by symptomatic and not actually the root cause of the issue. 

Unless you enabled "Logged-In Users" caching (**Comet Cache → Plugin Options → Logged-In Users**), Comet Cache does not do any caching whatsoever for logged-in users. I assume you're authenticating with the REST API to publish the album, so Comet Cache should not be getting in the way at all here.

**Comment by raamdev** [comment]
@midiman369 Sorry, I got the Envira Gallery Plugin mixed up with another plugin called Koken, which seems to produce the exact same "AgExportSession:recordRemoteCollectionId: remote ID must be a number or string" error. I did find [another thread](https://forums.adobe.com/thread/2087253) related to the Envira Gallery plugin where it's also suggested to contact the Envira Gallery support via [this link](http://enviragallery.com/contact/).

**Comment by midiman369** [comment]
I have worked on this already with Envira Gallery support.  After a number of tests the conclusion was that the issue is with Comet Cache Pro activated and enabled.

**Comment by jaswrks** [comment]
> conclusion was that the issue is with Comet Cache Pro activated and enabled

@midiman369 How was this concluded by them? It's the details that matter in a case like this. What was the issue with Comet Cache that prevented Envira Gallery from working as intended? If you're unsure, please ask them to contact us directly so the issue can be resolved. They can just post to this thread if they'd like.

Referencing internal/private ticket:
https://websharks.zendesk.com/agent/tickets/14518

**Comment by midiman369** [comment]
This was concluded based on the fact that when we disabled Comet Cache that publishing from Adobe Lightroom works.  On the surface, not being a wordpress plugin author myself, that seems pretty definitive.  I do not know where to begin to troubleshoot further from there.  Can you tell me what I may look at to troubleshoot further?

Also, I have just emailed Envira support regarding the issue, asking them assist further.  I have included the links to this thread.

**Comment by ericakfranz** [comment]
Hey team, I'm from Envira's support team and wanted to touch in on this. 

@midiman369 can you confirm if you downloaded/installed the Lightroom plugin present on your computer from your Envira Gallery account or directly through Adobe?

I ask because this error output has come up in the past and we patched it (not specifically related to Comet Cache), however Adobe doesn't release updates immediately so it's still possible to download the outdated version from their plugin repo. If you're not certain would you download it fresh from your Envira account and replace the instance on your computer to test if that resolves the error when publishing from Lightroom?

**Comment by midiman369** [comment]
Hi,

Yes the Lightroom Plugin is the version downloaded from my account page.

**Comment by raamdev** [comment]
Closing due to lack of feedback.
